"""Known issues database for LogSherlock Pro.

Contains 25+ pre-loaded known issues covering HPE products:
Morpheus, KVM, Alletra, GFS2, VME, Pacemaker.
"""

KNOWN_ISSUES = [
    {
        'title': 'GFS2 withdraw due to SCSI reservation conflict on shared LUN',
        'products': ['GFS2', 'Alletra'],
        'symptoms': 'GFS2 filesystem withdraw; SCSI reservation conflict in dmesg; I/O errors on shared device',
        'root_cause': 'When two cluster nodes simultaneously attempt I/O on a shared LUN without proper SCSI-3 PR coordination, reservation conflicts occur causing GFS2 to withdraw to protect data integrity.',
        'solution': '1. Verify SCSI-3 PR registrations (sg_persist --in -k /dev/mapper/mpathX)\n2. Check fencing agent configuration\n3. Restart DLM and GFS2 on affected node\n4. If persistent, check storage array for LUN masking issues',
        'bug_id': 'BZ-2024-1847',
        'affected_versions': 'RHEL 8.6-8.8, GFS2 all versions with Alletra 9000 series',
    },
    {
        'title': 'Morpheus provisioning fails with libvirt connection timeout',
        'products': ['Morpheus', 'KVM'],
        'symptoms': 'Instance creation fails; libvirt connection refused or timeout; morpheus-ui logs show "Failed to connect to hypervisor"',
        'root_cause': 'Morpheus worker connection pool exhaustion when multiple concurrent provisions are requested. The libvirtd socket accepts limited connections and morpheus does not gracefully handle pool exhaustion.',
        'solution': '1. Restart morpheus-ui service\n2. Increase libvirtd max_clients in /etc/libvirt/libvirtd.conf (default 5000)\n3. Check morpheus worker count vs hypervisor capacity\n4. Apply Morpheus patch 6.2.1-hotfix-3',
        'bug_id': 'MORPH-2024-0892',
        'affected_versions': 'Morpheus 6.0.x - 6.2.0',
    },
    {
        'title': 'KVM VM fails to start after host reboot - AppArmor denial',
        'products': ['KVM'],
        'symptoms': 'VM start fails with "Permission denied"; AppArmor denial in audit.log; domain XML references moved disk path',
        'root_cause': 'After host reboot, AppArmor profile for libvirt does not include dynamically added disk paths. If disk images were moved or new paths added without updating AppArmor, VMs cannot access their disks.',
        'solution': '1. Check /var/log/audit/audit.log for AppArmor denials\n2. Add disk path to /etc/apparmor.d/abstractions/libvirt-qemu\n3. Reload AppArmor: apparmor_parser -r /etc/apparmor.d/libvirt/TEMPLATE.qemu\n4. Or set security_driver = "none" in /etc/libvirt/qemu.conf (less secure)',
        'bug_id': 'KVM-2023-0445',
        'affected_versions': 'Ubuntu 20.04+, All KVM versions with AppArmor',
    },
    {
        'title': 'Alletra multipath failover causes 120-second I/O pause',
        'products': ['Alletra'],
        'symptoms': 'I/O hangs for 120 seconds during path failover; multipath shows paths switching; applications report timeout',
        'root_cause': 'Default SCSI timeout (30s) combined with multipath retry count (4) creates 120-second total timeout before failover completes. The dev_loss_tmo and fast_io_fail_tmo are not optimally configured for Alletra arrays.',
        'solution': '1. Set dev_loss_tmo=30 in multipath.conf for Alletra devices\n2. Set fast_io_fail_tmo=5\n3. Set no_path_retry=5\n4. Rebuild initramfs and reboot\n5. Verify with: multipathd show config local',
        'bug_id': 'ALT-2024-0156',
        'affected_versions': 'Alletra 6000/9000, All OS versions with default multipath settings',
    },
    {
        'title': 'Pacemaker fence race condition causes both nodes to reboot',
        'products': ['Pacemaker'],
        'symptoms': 'Both cluster nodes reboot simultaneously; fence history shows mutual fencing; split-brain detected',
        'root_cause': 'When corosync communication fails symmetrically (switch failure), both nodes lose contact simultaneously. Without proper quorum configuration, both nodes attempt to fence each other, causing a dual reboot.',
        'solution': '1. Configure proper quorum device (qdevice/qnetd)\n2. Set no-quorum-policy=suicide for 2-node clusters\n3. Use priority fencing with proper delay on one node\n4. Add fence_delay=5 to secondary node fence config',
        'bug_id': 'PCS-2024-0234',
        'affected_versions': 'Pacemaker 2.0.x - 2.1.x, 2-node cluster configurations',
    },
    {
        'title': 'GFS2 lock contention causes cluster-wide hang',
        'products': ['GFS2', 'Pacemaker'],
        'symptoms': 'All nodes accessing GFS2 become unresponsive; DLM lock waits > 60 seconds; processes in D state',
        'root_cause': 'Heavy small-file workload on GFS2 creates excessive DLM lock traffic. When lock requests exceed cluster network capacity, all nodes enter a deadlock-like state waiting for lock grants.',
        'solution': '1. Reduce concurrent file operations on GFS2\n2. Use local filesystem for temp/work directories\n3. Tune gfs2 lock_dlm parameters: mount -o noatime,nodiratime\n4. Increase corosync token timeout to prevent false fencing\n5. Consider using NFS exports from one node instead of direct GFS2 access from all',
        'bug_id': 'GFS2-2024-0078',
        'affected_versions': 'GFS2 on RHEL 8.x/9.x with > 4 nodes',
    },
    {
        'title': 'VME backup fails with snapshot creation timeout',
        'products': ['VME', 'KVM'],
        'symptoms': 'VME backup job fails; "snapshot creation timeout" in VME logs; qemu-img process stuck',
        'root_cause': 'VME snapshot creation uses qemu-guest-agent freeze/thaw. If the guest agent is not installed or unresponsive, the snapshot times out after 60 seconds and the backup fails.',
        'solution': '1. Verify qemu-guest-agent is installed and running in the VM\n2. Check guest agent socket: virsh qemu-agent-command <domain> \'{"execute":"guest-ping"}\'\n3. Increase VME snapshot timeout in config\n4. For Linux VMs, ensure qemu-ga service is enabled',
        'bug_id': 'VME-2024-0112',
        'affected_versions': 'VME 7.x with KVM hypervisors',
    },
    {
        'title': 'SMAD agent memory leak causes OOM kill',
        'products': ['Morpheus'],
        'symptoms': 'SMAD memory usage grows over days; eventually OOM killed; monitoring gaps after restart',
        'root_cause': 'SMAD agent leaks memory when processing metrics from VMs with frequently changing disk configurations. Each disk change event allocates monitoring structures that are never freed.',
        'solution': '1. Update SMAD to version 4.2.1+ (includes fix)\n2. Workaround: Schedule weekly SMAD restart via cron\n3. Set memory limit in systemd: MemoryMax=512M in smad.service\n4. Reduce metric collection frequency in smad.conf',
        'bug_id': 'SMAD-2024-0067',
        'affected_versions': 'SMAD 4.0.0 - 4.2.0',
    },
    {
        'title': 'Corosync token timeout causes unnecessary fencing',
        'products': ['Pacemaker'],
        'symptoms': 'Nodes fenced during high CPU load; corosync token timeouts in logs; system load > 50',
        'root_cause': 'Under heavy CPU load, corosync cannot process heartbeat tokens within the default timeout (1000ms). The cluster incorrectly assumes the node is dead and fences it.',
        'solution': '1. Increase corosync token timeout: token: 5000 in corosync.conf\n2. Set consensus: 7500 (1.2x token + token)\n3. Set corosync process to real-time priority\n4. Investigate root cause of high CPU load',
        'bug_id': 'COR-2023-0189',
        'affected_versions': 'Corosync 2.x/3.x with default token timeout',
    },
    {
        'title': 'Morpheus instance stuck in provisioning state',
        'products': ['Morpheus'],
        'symptoms': 'Instance shows "Provisioning" indefinitely; cloud-init completed; Morpheus agent installed but not reporting',
        'root_cause': 'Morpheus agent requires outbound HTTPS (443) to the Morpheus appliance. If firewall rules block this after VM provisioning, the agent cannot report completion and the instance stays in provisioning state.',
        'solution': '1. Verify network connectivity from VM to Morpheus appliance on port 443\n2. Check VM firewall rules (iptables/nftables)\n3. Verify Morpheus agent is running: systemctl status morpheus-node-agent\n4. Manually complete provisioning via API if network issue is resolved',
        'bug_id': 'MORPH-2024-0445',
        'affected_versions': 'Morpheus 5.x - 6.x',
    },
    {
        'title': 'Alletra volume offline after array controller failover',
        'products': ['Alletra'],
        'symptoms': 'LUNs go offline after controller failover; multipath shows all paths failed; applications lose access',
        'root_cause': 'During Alletra controller failover, LUN ownership transfers between controllers. If the host ALUA settings are incorrect, the host does not follow the LUN to the new controller path.',
        'solution': '1. Verify ALUA is enabled: sg_rtpg /dev/sdX\n2. Check multipath.conf has correct Alletra settings (path_grouping_policy=group_by_prio)\n3. Set prio=alua in multipath.conf\n4. Rescan SCSI: echo "- - -" > /sys/class/scsi_host/host*/scan',
        'bug_id': 'ALT-2024-0203',
        'affected_versions': 'Alletra 9000 with firmware < 9.4.1',
    },
    {
        'title': 'KVM live migration fails with "migration was active" error',
        'products': ['KVM', 'Morpheus'],
        'symptoms': 'Live migration fails; "migration was active" error; VM stays on source; destination cleanup required',
        'root_cause': 'A previous failed migration left stale state on the destination. Libvirt does not clean up properly when migration is interrupted, leaving the destination thinking a migration is in progress.',
        'solution': '1. On destination: virsh list --all (find the stale domain)\n2. virsh destroy <domain> on destination\n3. virsh undefine <domain> on destination\n4. Retry migration\n5. If persistent, restart libvirtd on destination',
        'bug_id': 'KVM-2024-0201',
        'affected_versions': 'libvirt 8.x - 9.x',
    },
    {
        'title': 'GFS2 fsck required after unclean shutdown',
        'products': ['GFS2'],
        'symptoms': 'GFS2 mount fails after power outage; "journal recovery failed"; filesystem marked dirty',
        'root_cause': 'After unclean shutdown (power loss, kernel panic), GFS2 journal replay may fail if the journal contains references to blocks that were being written during the crash.',
        'solution': '1. Try mounting with -o errors=continue to attempt journal replay\n2. If that fails, run fsck.gfs2 -y /dev/mapper/<vg>-<lv>\n3. After fsck, attempt mount again\n4. Verify data integrity after recovery\n5. Implement UPS and proper shutdown procedures',
        'bug_id': 'GFS2-2023-0445',
        'affected_versions': 'All GFS2 versions',
    },
    {
        'title': 'Pacemaker resource agent timeout during storage failover',
        'products': ['Pacemaker', 'Alletra'],
        'symptoms': 'Resource monitor timeout; pacemaker marks resource as failed; unnecessary failover triggered',
        'root_cause': 'Default resource monitor timeout (20s) is too short when storage is experiencing a path failover (which can take up to 120s with default multipath settings).',
        'solution': '1. Increase resource monitor timeout: pcs resource op update <resource> monitor timeout=180s\n2. Fix underlying multipath timeout (see Alletra multipath failover issue)\n3. Configure resource migration-threshold to tolerate brief failures',
        'bug_id': 'PCS-2024-0301',
        'affected_versions': 'Pacemaker 2.x with default resource timeouts',
    },
    {
        'title': 'VME incremental backup chain broken',
        'products': ['VME'],
        'symptoms': 'Incremental backup fails; "parent snapshot not found"; requires full backup to resume',
        'root_cause': 'When a VM snapshot is manually deleted or the VM is restored to a previous snapshot, the VME incremental backup chain is broken because the reference point no longer exists.',
        'solution': '1. Delete the broken backup chain in VME console\n2. Create a new full backup as the new base\n3. Avoid manually deleting snapshots that VME is tracking\n4. Configure VME retention to clean up old chains automatically',
        'bug_id': 'VME-2024-0089',
        'affected_versions': 'VME 6.x - 7.x',
    },
    {
        'title': 'Morpheus agent fails to install on RHEL 9 with FIPS enabled',
        'products': ['Morpheus'],
        'symptoms': 'Agent install script fails; SSL handshake error; FIPS mode blocks certain ciphers',
        'root_cause': 'Morpheus agent installer uses TLS ciphers that are not FIPS-compliant. When FIPS mode is enabled on RHEL 9, the SSL handshake fails during agent download.',
        'solution': '1. Update Morpheus appliance to 6.2.2+ (includes FIPS-compatible ciphers)\n2. Workaround: Manually download agent package and install offline\n3. Or temporarily add TLS 1.2 FIPS cipher to Morpheus nginx config',
        'bug_id': 'MORPH-2024-0678',
        'affected_versions': 'Morpheus 6.0.x - 6.2.1 with RHEL 9 FIPS mode',
    },
    {
        'title': 'Kernel OOM kills critical cluster processes',
        'products': ['Pacemaker', 'GFS2'],
        'symptoms': 'corosync or dlm_controld OOM killed; cluster loses quorum; GFS2 withdraws',
        'root_cause': 'Memory pressure from application workloads causes OOM killer to target cluster daemons. Default OOM score adjustment does not protect corosync/pacemaker adequately.',
        'solution': '1. Set OOM score adjust for critical processes: echo -1000 > /proc/$(pidof corosync)/oom_score_adj\n2. Add OOMScoreAdjust=-1000 to corosync.service and pacemaker.service\n3. Configure proper memory limits for application workloads\n4. Add swap space as a buffer',
        'bug_id': 'PCS-2023-0556',
        'affected_versions': 'All cluster versions on memory-constrained systems',
    },
    {
        'title': 'Alletra iSCSI login storm after network flap',
        'products': ['Alletra'],
        'symptoms': 'Hundreds of iSCSI login attempts; iscsid log filled with retries; brief network outage causes extended recovery',
        'root_cause': 'After a network flap, all iSCSI sessions attempt to reconnect simultaneously. The Alletra array rate-limits logins, causing cascading timeouts and extended recovery time.',
        'solution': '1. Configure node.session.timeo.replacement_timeout=30 in iscsid.conf\n2. Stagger session recovery with random delay\n3. Use multiple portals to distribute login load\n4. Configure Alletra to increase login queue depth',
        'bug_id': 'ALT-2024-0089',
        'affected_versions': 'Alletra 6000/9000 with iSCSI, > 32 sessions per host',
    },
    {
        'title': 'KVM nested virtualization crash with AMD EPYC',
        'products': ['KVM'],
        'symptoms': 'Guest kernel panic during nested VM boot; "KVM: entry failed" in host dmesg; AVIC-related errors',
        'root_cause': 'AMD AVIC (Advanced Virtual Interrupt Controller) conflicts with nested virtualization on EPYC 7003 series processors with certain firmware versions.',
        'solution': '1. Disable AVIC: echo "options kvm-amd avic=0" > /etc/modprobe.d/kvm-nested.conf\n2. Reload KVM module: modprobe -r kvm-amd && modprobe kvm-amd\n3. Or update host BIOS/firmware to latest version\n4. Verify with: cat /sys/module/kvm_amd/parameters/avic',
        'bug_id': 'KVM-2024-0334',
        'affected_versions': 'AMD EPYC 7003 series, kernel 5.15-6.1',
    },
    {
        'title': 'GFS2 performance degradation with many small files',
        'products': ['GFS2'],
        'symptoms': 'ls/stat operations take > 5 seconds; DLM lock count > 1M; cluster network saturated with lock traffic',
        'root_cause': 'GFS2 requires a DLM lock per inode. Directories with thousands of small files generate massive lock traffic across the cluster interconnect, causing performance degradation for all nodes.',
        'solution': '1. Restructure workload to use fewer, larger files\n2. Use local filesystem (ext4/xfs) for temporary/working data\n3. Reduce number of GFS2-accessing nodes\n4. Mount with noatime,nodiratime to reduce lock operations\n5. Consider NFS from single node for read-heavy workloads',
        'bug_id': 'GFS2-2024-0134',
        'affected_versions': 'All GFS2 versions with > 100K files per directory',
    },
    {
        'title': 'Morpheus workflow execution stalls after database connection pool exhaustion',
        'products': ['Morpheus'],
        'symptoms': 'Workflows stuck in running state; database pool exhaustion errors in morpheus-ui.log; all API calls slow',
        'root_cause': 'Long-running workflows hold database connections. When multiple workflows run concurrently, the connection pool is exhausted, blocking all other operations including health checks.',
        'solution': '1. Increase max pool size in morpheus.rb: db.pool.max=100\n2. Set connection timeout: db.pool.timeout=30000\n3. Identify and optimize long-running workflows\n4. Restart morpheus-ui to release stuck connections\n5. Monitor with: morpheus-ctl db-pool-status',
        'bug_id': 'MORPH-2024-0234',
        'affected_versions': 'Morpheus 6.x with default pool settings',
    },
    {
        'title': 'VME restore fails due to changed storage pool',
        'products': ['VME', 'KVM'],
        'symptoms': 'VM restore fails; "storage pool not found" error; backup metadata references deleted pool',
        'root_cause': 'VME stores the original storage pool UUID in backup metadata. If the pool was recreated or renamed after backup, the restore cannot find the target location.',
        'solution': '1. Create a storage pool with the same name as original\n2. Or use VME CLI to override restore target: vme restore --target-pool <new-pool>\n3. Edit backup metadata XML to update pool reference\n4. Verify target pool has sufficient space before restore',
        'bug_id': 'VME-2023-0567',
        'affected_versions': 'VME 6.x - 7.x',
    },
    {
        'title': 'Pacemaker constraint conflict prevents resource start',
        'products': ['Pacemaker'],
        'symptoms': 'Resource in Stopped state; "unmanaged" or "blocked" in pcs status; constraint violations in logs',
        'root_cause': 'Conflicting location constraints or colocation rules prevent the cluster from finding a valid node to start the resource. Often caused by accumulated ban constraints from previous failures.',
        'solution': '1. Check constraints: pcs constraint show --full\n2. Remove stale ban constraints: pcs resource clear <resource>\n3. Review location constraints for conflicts\n4. Check resource-stickiness and migration-threshold settings\n5. pcs resource cleanup <resource> to clear failure counts',
        'bug_id': 'PCS-2024-0167',
        'affected_versions': 'Pacemaker 2.x',
    },
    {
        'title': 'SMAD fails to monitor VMs after libvirtd restart',
        'products': ['Morpheus', 'KVM'],
        'symptoms': 'SMAD shows VMs as offline; monitoring gaps; libvirt connection "reset by peer" in SMAD logs',
        'root_cause': 'SMAD caches libvirt connection handles. When libvirtd is restarted, cached connections become invalid but SMAD does not reconnect until its own restart.',
        'solution': '1. Restart SMAD: systemctl restart smad\n2. Apply SMAD 4.2.2+ which includes connection recovery\n3. Monitor SMAD health after any libvirtd maintenance\n4. Add systemd dependency: After=libvirtd.service in smad.service',
        'bug_id': 'SMAD-2024-0112',
        'affected_versions': 'SMAD 4.0.x - 4.2.1',
    },
    {
        'title': 'Network bond failover causes ARP cache poisoning',
        'products': ['KVM', 'Pacemaker'],
        'symptoms': 'Network connectivity lost after bond failover; upstream switch shows wrong MAC; gratuitous ARP not received',
        'root_cause': 'When a bond fails over to the backup NIC, gratuitous ARP packets are sent to update upstream switch MAC tables. If the switch ARP timeout is long or gratuitous ARP is filtered, connectivity is lost until the switch cache expires.',
        'solution': '1. Configure bond with arp_interval=100 and arp_validate=all\n2. Verify switch accepts gratuitous ARP\n3. Set bond updelay=200 to stabilize before sending traffic\n4. For mode=1, set primary_reselect=better\n5. Manually clear ARP on switch if urgent: clear arp-cache',
        'bug_id': 'NET-2024-0078',
        'affected_versions': 'All Linux bonding versions with layer-2 switches',
    },
    {
        'title': 'Alletra deduplication causes latency spikes during garbage collection',
        'products': ['Alletra'],
        'symptoms': 'Periodic latency spikes every 4-6 hours; I/O latency > 100ms during spikes; array "gc" process active',
        'root_cause': 'Alletra deduplication garbage collection runs periodically to reclaim space from deleted deduplicated blocks. On heavily utilized arrays, this process competes with production I/O.',
        'solution': '1. Schedule GC during low-I/O windows via array management\n2. Increase GC throttle setting on the Alletra array\n3. If latency is unacceptable, consider disabling dedup for latency-sensitive volumes\n4. Ensure array is not > 80% capacity (GC becomes more aggressive)',
        'bug_id': 'ALT-2024-0345',
        'affected_versions': 'Alletra 9000 with deduplication enabled, capacity > 70%',
    },
    {
        'title': 'iptables rules lost after HVM host reboot - missing iptables-persistent',
        'products': ['Morpheus', 'HVM'],
        'symptoms': 'After server reboot, iptables rules are gone. Servers cannot communicate. Cluster loses quorum. Ports 443, 9200, 9300, 5672, 3306 become unreachable between nodes. Self-fencing risk.',
        'root_cause': 'iptables-persistent package not installed on Ubuntu/Debian HVM hosts. iptables rules are held in memory only and flushed on reboot. Morpheus 9.0.x installer does not install iptables-persistent as prerequisite.',
        'solution': '1. Install iptables-persistent: apt-get install iptables-persistent\n2. Save current rules: iptables-save > /etc/iptables/rules.v4\n3. Enable service: systemctl enable netfilter-persistent\n4. Reboot and verify: iptables -L -n\n\nApply to ALL HVM hosts in rolling fashion (one at a time to maintain quorum).',
        'bug_id': 'MORPHL4-77',
        'affected_versions': 'Morpheus Enterprise 9.0.0-2, 9.0.x on Ubuntu/Debian HVM hosts',
        'prevention': 'Add iptables-persistent to Morpheus HVM host setup prerequisites. Add post-reboot health check script. Include in pre-upgrade checklist.',
        'related_issues': 'Netplan apply required on hosts 02/04/06 after reboot (possible Aruba CX plugin residual). Self-fencing risk if multiple nodes reboot simultaneously.',
        'category': 'network',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'Netplan apply required after reboot for storage access',
        'products': ['Morpheus', 'HVM', 'Network'],
        'symptoms': 'After server reboot, storage network not accessible. Hosts require manual netplan apply to restore storage connectivity. Only affects specific hosts (not all).',
        'root_cause': 'Possible residual network configuration from previously used Aruba CX plugin. Netplan configuration may have ordering/dependency issue that prevents automatic application on boot.',
        'solution': '1. Check /etc/netplan/*.yaml for correct config\n2. Run netplan apply on affected hosts\n3. Remove any residual Aruba CX plugin config\n4. Verify with: ip addr show and ping storage targets\n5. Consider adding netplan apply to post-boot script as temporary workaround.',
        'bug_id': 'MORPHL4-77 (secondary)',
        'affected_versions': 'Morpheus 9.0.x with previous Aruba CX plugin usage',
        'prevention': 'Clean removal procedure for Aruba CX plugin. Verify netplan configs after plugin removal.',
        'related_issues': 'Related to iptables-persistent issue. Both occur post-reboot.',
        'category': 'network',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'VMDK deployment fails on Alletra vVOL Datastore',
        'products': ['Alletra', 'Morpheus', 'Storage'],
        'symptoms': 'Unable to deploy a VMDK to an Alletra vVOL (Virtual Volume) Datastore. Deployment fails with storage error.',
        'root_cause': 'VASA provider connectivity issue, protocol endpoint not accessible, or vVOL datastore not properly configured for VMDK format.',
        'solution': '1. Verify VASA provider is registered and healthy\n2. Check Alletra array connectivity\n3. Verify protocol endpoints are accessible from all hosts\n4. Check VMDK compatibility with vVOL datastore type\n5. Review Morpheus datastore configuration.',
        'bug_id': 'MORPHL4-84',
        'affected_versions': 'Morpheus with Alletra vVOL integration',
        'prevention': 'Verify vVOL datastore compatibility before VMDK deployment. Monitor VASA provider health.',
        'related_issues': 'May relate to Alletra array replication or protocol endpoint issues.',
        'category': 'storage',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'Cluster self-fencing in 2-node VME environment with external worker',
        'products': ['VME', 'Pacemaker', 'Corosync'],
        'symptoms': 'Cluster self-fencing occurs in VME 9.0.0_2 with 2-node setup and external worker. Nodes fence each other unexpectedly.',
        'root_cause': 'In 2-node clusters, quorum calculation is sensitive. If communication between nodes fails (even briefly), both nodes may attempt to fence the other. External worker node may not properly participate in quorum voting.',
        'solution': '1. Verify corosync communication between all nodes\n2. Check two_node: 1 setting in corosync.conf\n3. Verify external worker quorum participation\n4. Review fence device configuration\n5. Check network stability between nodes\n6. Consider wait_for_all: 1 to prevent startup fencing.',
        'bug_id': 'MORPHL4-80',
        'affected_versions': 'VME 9.0.0_2, 2-node configurations',
        'prevention': 'Use 3+ node clusters for production. Configure proper fence delays. Add network redundancy for corosync.',
        'related_issues': 'Related to iptables persistence issue - if iptables lost on reboot, cluster communication fails causing fencing.',
        'category': 'cluster',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'GFS2 volumes unusable without PR reservation keys on storage LUN',
        'products': ['GFS2', 'Alletra', 'Storage'],
        'symptoms': 'Unable to use GFS2 volumes on 9.x environment. System does not use PR (Persistent Reservation) keys but they exist on the storage LUN. GFS2 mount fails or goes read-only.',
        'root_cause': 'SCSI Persistent Reservations (PR) keys left on storage LUN from previous configuration. If the system is not configured to use PR keys but they exist on the LUN, GFS2 cannot properly manage locks.',
        'solution': '1. Check PR keys on LUN: sg_persist -i -k /dev/mapper/<device>\n2. Clear stale PR keys: sg_persist --out --clear --param-rk=<key> /dev/mapper/<device>\n3. Verify GFS2 mount options\n4. Restart GFS2/DLM services\n5. Verify with: dlm_tool status',
        'bug_id': 'MORPHL4-46',
        'affected_versions': 'Morpheus 9.x with GFS2 and Alletra storage',
        'prevention': 'Clean PR keys when decommissioning nodes. Document PR key management in runbook.',
        'related_issues': 'Related to MORPHL4-85 GFS2 datastore reclassification issue.',
        'category': 'storage',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'VME 8.1.0 GFS2 glock deadlock causes mass VM shutdown (heartbeat isolation)',
        'products': ['VME', 'GFS2', 'Pacemaker', 'Alletra'],
        'symptoms': 'All VMs on a host shut down automatically without failover. Agent logs show "Unable to Write Heartbeat" followed by "All heartbeat datastore paths have been unhealthy for 6 checks. Shutting down all VMs to protect data integrity". Kernel logs show processes blocked in D-state in gfs2_glock_wait/gfs2_create_inode for 122+ seconds. No network errors. 2-3 minute gap in syslog between VM start and mass shutdown. Some VMs may survive if their QEMU processes are also hung in D-state (cannot receive shutdown signal).',
        'root_cause': 'After upgrade to VME 8.1.0, concurrent operations on GFS2 filesystem trigger a glock (global lock) deadlock. The typical trigger sequence is: VM start -> SCSI host rescan (echo "- - -" > /sys/class/scsi_host/host*/scan) -> GFS2 pool refresh (virsh pool-refresh) -> Pacemaker resource meta update on live GFS2 clone. This creates glock contention that deadlocks the entire GFS2 filesystem. Since the heartbeat agent (MvmHeartbeatFailover) writes hb.properties to GFS2, it cannot write heartbeats. After 6 consecutive failures (MAX_ISOLATION_FAIL_COUNT=6, every 20 seconds), the agent triggers emergency shutdown of all VMs. The VME Manager VM is also shut down, preventing cluster-wide failover. Other nodes cannot read the affected host hb.properties file (also on deadlocked GFS2), so they never detect the host as offline and never initiate recovery.',
        'solution': '1. Immediate: Controlled reboot of affected host to clear stale GFS2 locks\n2. Manually restart VMs after confirming GFS2 is healthy\n3. Upgrade to VME 8.1.2+ which contains fix for MORPH-11774\n4. Configuration tuning: Increase morphd heartbeat timeout for larger buffer\n5. Ensure VME Manager VM has memory reservation to survive resource contention\n6. Long-term: HPE replacing Pacemaker/GFS2-based coordination in VME 9.0+',
        'bug_id': 'MORPH-11774',
        'affected_versions': 'VME 8.1.0 (regression from 8.0.13 upgrade)',
        'prevention': 'Upgrade to VME 8.1.2+. Avoid concurrent SCSI rescans + GFS2 pool refreshes + pcs resource updates. Pin VME Manager memory. Monitor GFS2 glock statistics.',
        'related_issues': 'MORPHL4-21, MORPHL4-85 (GFS2 datastore reclassification). Affects HVM 1.2 cluster layouts where GFS2 used for heartbeat even when VM data is on Alletra MP.',
        'category': 'cluster',
        'resolution_type': 'Software bug',
    },
    {
        'title': 'Morpheus datastore decommission race condition causes cluster-wide STONITH fencing cascade',
        'products': ['Morpheus', 'Pacemaker', 'GFS2', 'DLM'],
        'symptoms': 'During datastore decommission via Morpheus UI, cluster goes down unexpectedly. All remaining datastores transition to read-only state. STONITH fencing events across multiple/all nodes. DLM service failures. ~300+ VMs impacted. Cluster cannot auto-recover because STONITH configuration references deleted device paths. FSCK required on all affected GFS2 volumes before remount.',
        'root_cause': 'Software defect in the Morpheus datastore decommissioning workflow. When a datastore is marked as Stopped in Morpheus, the platform immediately removes the associated Pacemaker resource configuration WITHOUT waiting for the underlying GFS2 unmount operation to complete. If the unmount does not complete within the timeout (e.g., because the datastore still has active I/O), the GFS2 resource becomes orphaned — still mounted but no longer managed by Pacemaker. To protect shared filesystem integrity and prevent split-brain, Pacemaker initiates automatic STONITH fencing across affected nodes. As part of the cluster protection mechanism, all shared GFS2 volumes are transitioned to read-only mode, DLM and multipath services fail, and remaining clustered datastores become unavailable. The cluster cannot unfence automatically because STONITH configuration still references the deleted device path.',
        'solution': '1. Immediate: Full cluster node reboots to restore baseline availability\n2. Run FSCK (fsck.gfs2) on ALL affected datastores before remounting — do NOT skip this\n3. Process datastores in parallel, prioritize critical production dependencies\n4. Mount only after successful FSCK validation\n5. Phased VM restoration across recovered datastores\n6. Long-term fix: Upgrade to Morpheus v9.x where storage orchestration is handled by Morpheus agent directly (eliminates Pacemaker dependency)\n7. Workaround for older versions: NEVER decommission datastores via Morpheus UI. Instead: manually unmount GFS2 → remove Pacemaker resource → then remove from Morpheus.',
        'bug_id': 'MORPH-13237',
        'affected_versions': 'Morpheus/VME versions using legacy Pacemaker-based storage orchestration (pre-9.x)',
        'prevention': 'Do NOT use Morpheus UI to decommission datastores with GFS2/Pacemaker integration. Always verify datastore has zero active I/O before decommission. Upgrade to VME 9.x. Maintain valid STONITH device paths even for retired storage.',
        'related_issues': 'Related to MORPHL4-21 (GFS2 deadlock), MORPHL4-85 (GFS2 datastore reclassification). Grasten PC cluster P1 outage.',
        'category': 'cluster',
        'resolution_type': 'Software bug',
    },
    {
        'title': 'Faulty NIC link flapping causes DLM stateful merge cluster-wide kill (36.5-hour outage)',
        'products': ['Pacemaker', 'Corosync', 'DLM', 'GFS2'],
        'symptoms': 'NIC link flapping (hundreds of link-down events escalating daily). Corosync KNET links dropping. TOTEM token timeouts. Cluster splits into two partitions. When partitions rejoin, DLM detects stateful merge and kills ALL nodes via corosync. Corosync exits with status -1/255 and does NOT restart (no Restart= in systemd unit). Pacemaker retries corosync connection every second indefinitely. All VMs on GFS2 become Unknown/Off/Corrupted. 36+ hour outage until manual intervention.',
        'root_cause': 'Faulty NIC port (e.g., Intel ICE 25GbE) suffers escalating link failures (20/day → 314/day over one week). The NIC carries cluster heartbeat traffic via LACP bond. Each flap disrupts LACP negotiation and causes packet loss exceeding Corosync TOTEM token timeout (3712ms). Eventually a prolonged link-down (6+ minutes) causes cluster split-brain. When the NIC briefly recovers, partitions attempt to rejoin. DLM detects that lock states diverged during the split (stateful merge condition). DLMs defined response is to kill ALL nodes to prevent corrupted lock state. dlm_controld instructs corosync to remove nodes, causing corosync to exit with status -1. Since corosync.service has no Restart= directive, it stays dead. Pacemaker cannot manage any resources. All VMs become unmanaged.',
        'solution': '1. Immediate: Manually restart corosync on all nodes (systemctl start corosync)\n2. Verify cluster reforms and GFS2 journals replay successfully\n3. Run fsck on affected VM guest volumes (potential corruption from abrupt I/O severance)\n4. Replace faulty NIC (check bond slave stats for link failure count)\n5. Add Restart=on-failure to corosync.service systemd unit on ALL nodes\n6. Add redundant Corosync ring (configure rrp_mode or second ring_addr)\n7. Consider changing no-quorum-policy from freeze to fence/stop\n8. Monitor NIC link failure count proactively (alert at >10/day)',
        'bug_id': 'MORPHL4-25',
        'affected_versions': 'All Pacemaker/Corosync/DLM/GFS2 cluster configurations with single corosync ring',
        'prevention': 'Monitor NIC link failure counts daily. Alert on any non-zero link failures. Configure redundant corosync rings. Add Restart=on-failure to corosync.service. Replace NICs showing any link instability before they cause cluster events.',
        'related_issues': 'MORPHL4-21 (GFS2 deadlock), MORPHL4-85 (GFS2 reclassification). Contributing factor: SCSI ALUA storage event 3.5 hours before added I/O stress.',
        'category': 'cluster',
        'resolution_type': 'Hardware fault + Configuration gap',
    },
    {
        'title': 'Orphaned LUN accumulation from failed backups causes multipath saturation and cluster collapse (HV-3624)',
        'products': ['Alletra', 'VME', 'Morpheus', 'Pacemaker', 'GFS2'],
        'symptoms': 'multipathd commands take 30-60 seconds (should be milliseconds). lsblk output exceeds 178,000 lines. Load average >60-189. OOM killer firing on QEMU VMs and pacemaker-fenced. STONITH fencing device disappears from /dev/disk/by-uuid/. Fence retries every 15 minutes failing. LUN count grows from ~150 to 5,800+. Backup success rate drops from 95% to 0%. VMs start running on multiple hosts. Filesystem corruption on guest volumes.',
        'root_cause': 'Software defect in HPE Alletra plugin (HV-3624): Every failed backup/snapshot-export silently leaves a permanent orphaned LUN mapping on the storage array. The cleanup code at DatastoreUtil.groovy:1413 has a TODO comment but is NOT implemented. This creates a self-reinforcing feedback loop: failed snapshot → orphaned LUN stays mapped → more LUNs → slower multipathd → more snapshot failures → more orphaned LUNs. Over 30 days, LUN count grew from 258 to 5,817 (~81 orphan snapshots per base volume). With 5,800+ LUNs × 2-4 FC paths = 12,000-23,000 SCSI paths, multipathd saturates. STONITH fence_scsi commands timeout (cannot enumerate registrations across 5,800 LUNs). Fencing fails → cluster cannot safely evict nodes → Morpheus starts VMs on another host while still running on original → VMs running on multiple hosts → disk corruption.',
        'solution': '1. IMMEDIATE: Suspend ALL backup schedules to stop orphaned LUN growth\n2. On storage array: identify orphaned snapshot application sets with no active backup record\n3. Unmap orphaned LUNs from Host Set (does NOT delete data, reduces LUN count immediately)\n4. After unmap: multipathd -k reconfigure on all nodes\n5. Verify: multipath -ll responds in <5 seconds, lsblk | wc -l <500\n6. Fix STONITH device (re-present or reconfigure)\n7. Fix split-brain VMs: virsh destroy duplicates, fsck guest volumes\n8. Do NOT re-enable backups until HV-3624 is fixed (available in plugin 9.0.2)\n9. If backups must resume: use very low frequency and stagger VMs in small batches.',
        'bug_id': 'HV-3624',
        'affected_versions': 'HPE Alletra plugin (all versions before 9.0.2) with VME 8.0.x',
        'prevention': 'Apply plugin 9.0.2 (implements cleanup on failed snapshot export). Monitor LUN count weekly (should be close to VM count, not 10-100x). Alert if multipath -ll takes >5 seconds. Use low-frequency backup schedules. Implement weekly orphan LUN audit script.',
        'related_issues': 'MORPH-7948 (VM running on multiple hosts fix in 8.0.13-3). MORPHL4-26 P1 cluster collapse.',
        'category': 'storage',
        'resolution_type': 'Software bug',
    },
    {
        'title': 'VM running on multiple hosts due to failed fencing (split-brain VM duplication - MORPH-7948)',
        'products': ['VME', 'Morpheus', 'Pacemaker'],
        'symptoms': 'Same VM instance running simultaneously on 2+ hosts. VM filesystem corruption. virsh list shows same domain on multiple nodes. Morpheus UI shows VM on one host but virsh shows it on another. VMs in Unknown/Off/Corrupted state in UI. Guest OS filesystem errors on boot after recovery.',
        'root_cause': 'When STONITH fencing fails (device missing, timeout, or unavailable), Pacemaker cannot safely evict a node from the cluster. However, Morpheus orchestrator may still decide to start the VM on another "healthy" node — while the original instance is still running on the unfenced node. This creates a split-brain at the VM level: two QEMU processes writing to the same virtual disk simultaneously. In VME 8.0.11, there is a race condition (MORPH-7948) where the VM start proceeds without confirming the original instance was actually stopped. Any shared writes during this period corrupt the virtual disk.',
        'solution': '1. Identify duplicates: run virsh list --all on EVERY cluster node, compare\n2. Determine authoritative host (check Morpheus UI)\n3. On WRONG host: virsh destroy <domain> && virsh undefine <domain>\n4. After cleanup: check guest disk integrity (mount and fsck guest volume)\n5. For corrupted VMs: restore from last good backup\n6. Apply MORPH-7948 fix: upgrade to VME 8.0.13-3 or higher\n7. Fix the underlying fencing issue to prevent recurrence.',
        'bug_id': 'MORPH-7948',
        'affected_versions': 'VME 8.0.11 and earlier (fixed in 8.0.13-3)',
        'prevention': 'Upgrade to VME 8.0.13-3+. Ensure STONITH is always functional. Disable "Automatically Power On VMs" in Morpheus if fencing is degraded. Monitor fence status and alert on failures.',
        'related_issues': 'HV-3624 (orphaned LUN accumulation destroys fencing device). MORPHL4-26.',
        'category': 'virtualization',
        'resolution_type': 'Software bug',
    },
    {
        'title': 'Cluster upgrade from 1.2 to 1.3 kills cluster when powered-off VMs cannot be migrated',
        'products': ['VME', 'Pacemaker', 'Morpheus'],
        'symptoms': 'After upgrading VME to 9.0.0 and attempting cluster upgrade from 1.2 to 1.3, the cluster goes down. Error message: "VM Essentials, Skipped: VM is powered off and movePoweredOff is disabled". Cluster process fails but does not roll back cleanly. pcs cluster status returns "Error: cluster is not currently running on this node". DLM and GFS2 datastores become unmounted.',
        'root_cause': 'The cluster upgrade process from 1.2 to 1.3 attempts to migrate all VMs off each node before upgrading it. When it encounters powered-off VMs, it cannot migrate them (movePoweredOff is disabled by default). The process logs a skip/error but continues with the upgrade, which disrupts cluster services. The upgrade does not properly handle the case where VMs are in a non-running state, leaving the cluster in a broken state with corosync/pacemaker stopped.',
        'solution': '1. Restart all cluster nodes (rolling reboot)\n2. Verify corosync starts: systemctl status corosync\n3. Verify DLM mounts datastores: pcs status, mount | grep gfs2\n4. Prevention: Before upgrading cluster 1.2→1.3, ensure ALL VMs are either running (so they can be migrated) or manually moved/unregistered from the node\n5. Alternative: Enable movePoweredOff before upgrade if possible.',
        'bug_id': 'MORPHL4-27 (tracking)',
        'affected_versions': 'VME 9.0.0 with cluster upgrade from 1.2 to 1.3',
        'prevention': 'Before cluster upgrade: power on all VMs or manually move powered-off VMs to a single node. Verify no VMs are in off/suspended state across nodes being upgraded. Take cluster backup (pcs config backup) before upgrade.',
        'related_issues': 'General cluster upgrade issues. VME 9.0.x cluster management.',
        'category': 'cluster',
        'resolution_type': 'Operational (workaround available)',
    },
    {
        'title': 'Data center power outage causes GFS2 metadata corruption — all cluster resources stopped, manual fsck required',
        'products': ['GFS2', 'Pacemaker', 'DLM', 'VME', 'Alletra'],
        'symptoms': 'After abrupt DC power loss, all GFS2 cluster resources show Stopped. DLM-clone stopped on all nodes. Manual mount attempts fail with "wrong fs type, bad option, bad superblock". pcs resource enable does not bring resources up. Some nodes fail to rejoin cluster post-power-restoration (quorum loss). All production VMs inaccessible. fsck.gfs2 required on every affected datastore before mount succeeds.',
        'root_cause': 'Instantaneous power loss interrupts active I/O before commits to disk, leaving GFS2 journals in inconsistent state (journal desynchronization). On power restoration: (1) Some nodes have hardware/connectivity issues and cannot rejoin — causing quorum loss which prevents DLM from starting. (2) Without DLM, GFS2 cannot mount (requires lock_dlm protocol). (3) Even with quorum restored (via node eviction), the GFS2 superblock/metadata is corrupted from unclean shutdown — journals cannot replay automatically. Contributing factors: No graceful shutdown mechanism (no UPS-triggered pcs node standby), NBD/LVM interaction from Commvault backups creating device locks (known 8.0.x defect), excessive heartbeat datastore count (12 vs recommended 2-3).',
        'solution': '1. Restore quorum first: if nodes cannot rejoin, evict them (pcs cluster node remove <node>)\n2. Verify DLM starts: pcs resource enable dlm-clone, dlm_tool status\n3. Disable all GFS2 resources: pcs resource disable <resource>\n4. Run fsck.gfs2 -y on EVERY affected mapper device (all 12 datastores)\n5. Re-enable resources sequentially: pcs resource enable <resource> (one at a time)\n6. Verify mounts: mount | grep gfs2\n7. Start VMs once all datastores are online\n8. For stubborn volumes: repeat fsck.gfs2, check for stale journals from evicted nodes',
        'bug_id': 'MORPH-14174 (elevated to engineering)',
        'affected_versions': 'Morpheus 8.0.13 and all 8.0.x with Pacemaker/GFS2 cluster architecture',
        'prevention': 'Implement UPS-triggered graceful shutdown (pcs node standby on power loss signal). Apply LVM filter in /etc/lvm/lvm.conf to exclude /dev/nbd* devices. Reduce heartbeat datastore count to 2-3 (not 12). Upgrade to 9.x (removes Pacemaker, uses agent-based quorum). Keep spare nodes to maintain quorum after failures.',
        'related_issues': 'MORPHL4-28, PCS-1886. Historical: PCS-995 (CIB mismatch), PCS-1826 (datastore decommission), MORPHL4-21 (GFS2 deadlock), MORPHL4-26 (fencing device lost). Architecture redesigned in Morpheus 9.x (Cluster Layout 1.3 removes Pacemaker).',
        'category': 'cluster',
        'resolution_type': 'Architectural limitation (fix in 9.x)',
    },
    {
        'title': 'Backup restore and clone fail with "Instance is not valid" when source image is deleted (MORPH-13534)',
        'products': ['VME', 'Morpheus'],
        'symptoms': 'Restore-to-new-instance and Clone operations fail with UI error "Instance is not valid". Morpheus logs show NullPointerException: Cannot get property \'locations\' on null object at VirtualImageService.findVirtualImageLocationRecord(). Affects any VM whose original source ISO/image was deleted from the Morpheus Library, or VMs that were migrated and have no associated image. Original VM continues to run fine — only restore/clone is broken.',
        'root_cause': 'Software defect in Morpheus validation workflow. During Clone/Restore, InstanceService.validateInstance() calls VirtualImageService.findVirtualImageLocationRecord() which attempts to resolve the original source Virtual Image. If the image was deleted, the lookup returns null. The code then accesses .locations on null without a null check, causing NullPointerException. The validation treats this as a fatal error and blocks the operation, even though the VM, backup data, and storage are all healthy and usable.',
        'solution': 'WORKAROUND (API bypass):\\n\\nFor CLONE:\\ncurl -k -X PUT "https://<appliance>/api/instances/<instance_id>/clone" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d \'{ "name": "<clone-name>", "config": {"imageId": -1}, "provisionPoweredOff": true }\'\\n\\nFor RESTORE:\\ncurl -k -X POST "https://<appliance>/api/backups/restores" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d \'{"restore": {"backupResultId": <id>, "instanceId": <id>, "restoreInstance": "new", "provisionPoweredOff": true, "instance": {"name": "<name>", "group": {"id": <gid>}, "cloud": {"id": <cid>}, "layout": {"id": <lid>}, "plan": {"id": <pid>}, "type": "mvm", "provisionType": "kvm", "config": {"imageId": -1, "resourcePoolId": "<rpid>"}, "volumes": [{"rootVolume": true, "name": "root", "size": 100, "storageType": <stid>, "datastoreId": "auto"}], "networkInterfaces": [{"network": {"id": "<nid>"}, "networkInterfaceTypeId": <nitid>}]}}}\'\\n\\nKey: "imageId": -1 bypasses the source image validation.\\nPermanent fix: upgrade to 9.0.1.22+ (MORPH-13534).',
        'bug_id': 'MORPH-13534',
        'affected_versions': 'VME 8.0.x and 9.0.x (fixed in 9.0.1.22)',
        'prevention': 'Do not delete source images from Morpheus Library if any VM was created from them and may need restore/clone in the future. If image must be deleted, document the API workaround for affected VMs.',
        'related_issues': 'MORPHL4-29. Separate but related: KvmProvisionService.applyDiskConfig() NullPointerException if volumes not specified in restore API payload.',
        'category': 'application',
        'resolution_type': 'Software bug',
    },
    {
        'title': 'PCBE upgrade creates Pacemaker version mismatch — infinite DC election storm, node stuck in pending',
        'products': ['Pacemaker', 'VME', 'Corosync'],
        'symptoms': 'After PCBE Single Click Upgrade upgrades one node (Pacemaker 2.1.2 → 2.1.6), the upgraded node cannot rejoin the cluster. pcs status shows node as "pending". Logs show "Discarding update with feature set 3.17.4 greater than our own 3.11.0" and "Protocol not supported (rc=-93)". Infinite DC election cycle (31+ million rounds). /var/log fills completely from election log spam. rsyslog begins losing messages. Current DC shows NONE on upgraded node.',
        'root_cause': 'Pacemaker version-based DC election algorithm causes the newer node (2.1.6, feature set 3.17.4) to consistently win DC elections. When it becomes DC, it distributes its CIB with feature set 3.17.4. The older nodes (2.1.2, feature set 3.11.0) immediately reject it. The CIB sync failure triggers a new election. This creates an infinite loop that fills disk with logs and prevents the cluster from stabilizing. The PCBE SCU upgrade script upgraded one node but then failed to continue upgrading the remaining nodes, leaving the cluster in a mixed-version state.',
        'solution': '1. IMMEDIATE: Stop pacemaker and corosync on the upgraded node (systemctl stop pacemaker corosync)\n2. Truncate logs: truncate -s 0 /var/log/pacemaker/pacemaker.log\n3. Reduce log verbosity: set PCMK_logpriority=warning in /etc/default/pacemaker\n4. Verify remaining nodes form healthy cluster\n5. RESOLUTION: Upgrade remaining nodes to same Pacemaker version (manual upgrade via DSCVM if SCU cannot proceed)\n6. After all nodes on same version: start corosync first, then pacemaker on upgraded node\n7. Alternative: if downtime acceptable, stop all cluster services, upgrade all nodes, restart in order\n8. Do NOT attempt to downgrade the already-upgraded node.',
        'bug_id': 'MORPH-13840',
        'affected_versions': 'PCBE with VME Host OS upgrade from 1.0.0.42 (Ubuntu 22.04, Pacemaker 2.1.2) to 3.0.0.12 (Ubuntu 24.04, Pacemaker 2.1.6)',
        'prevention': 'PCBE SCU must upgrade all nodes in rapid succession without allowing mixed-version operation. Pin Pacemaker version in OS image builds. Test upgrade path in lab before production. Ensure upgrade script does not allow partial completion that leaves cluster in mixed state.',
        'related_issues': 'MORPHL4-30, MORPHL4-71 (similar SCU upgrade failure). The cluster CANNOT operate with mixed Pacemaker versions — all nodes MUST be on the same version.',
        'category': 'cluster',
        'resolution_type': 'Operational (upgrade remaining nodes)',
    },
    {
        'title': 'GFS2 space not reclaimed after file deletion — orphaned allocation metadata (kernel bug)',
        'products': ['GFS2', 'VME'],
        'symptoms': 'df shows significantly more used space than du reports. Large gap between GFS2 reported usage and visible file allocation (e.g., 903 GiB gap). Deleting files from Morpheus GUI does not free space. fstrim/discard reclaims negligible space. Space discrepancy is consistent across ALL cluster nodes. No hidden mounts, no qualifying open-deleted files (memfd excluded). Space never comes back without fsck.',
        'root_cause': 'GFS2 kernel bug: When a file is deleted while still open by a process (e.g., QEMU, libvirt, or Morpheus operations), the space is not returned to the filesystem after the process exits. GFS2 with rgrplvb (Resource Group Lock Value Block) caching does not properly reclaim blocks from open-deleted files. The filesystem believes blocks are still allocated even though no visible file references them. sync, drop_caches, remount, and fstrim do NOT fix this. Only fsck.gfs2 recovers the space. Fixed in kernel 6.8.0-117-generic with linux-modules-extra package.',
        'solution': '1. CONFIRM: Compare df vs du on the GFS2 mount (large gap = this issue)\n2. VERIFY: lsof +L1 <mount> | grep -v memfd (exclude QEMU memory objects)\n3. SHORT-TERM: Schedule maintenance window, unmount GFS2 on all nodes\n4. RUN: fsck.gfs2 -n /dev/mapper/<device> (read-only check first)\n5. If inconsistencies found: fsck.gfs2 -y /dev/mapper/<device>\n6. LONG-TERM FIX: Upgrade kernel to 6.8.0-117-generic or later\n7. Also install: apt install linux-modules-extra-6.8.0-117-generic (GFS2 module)',
        'bug_id': 'MORPHL4-31 (kernel bug, fixed in 6.8.0-117)',
        'affected_versions': 'All GFS2 on kernels before 6.8.0-117-generic with rgrplvb mount option',
        'prevention': 'Upgrade kernel to 6.8.0-117+. Monitor df vs du gap weekly. Alert if gap exceeds 10% of filesystem size. Schedule periodic fsck during maintenance windows if kernel upgrade is not immediately possible.',
        'related_issues': 'MORPHL4-28 (Danfoss GFS2 corruption). Similar symptom but different root cause — this is a space leak, not metadata corruption from power loss.',
        'category': 'filesystem',
        'resolution_type': 'Kernel bug (fixed in 6.8.0-117)',
    },
    {
        'title': 'Post-upgrade false heartbeat failure on single host causes automatic VM shutdown despite healthy cluster (VME 9.0.1.17)',
        'products': ['VME', 'Morpheus'],
        'symptoms': 'After upgrading to VME 9.0.1.17 with agents 3.2.6, a SINGLE host fails all heartbeat checks. VMs provisioned on or migrated to that host are automatically powered off. VM start fails ("server start failed"). Migration away fails ("domain is not running"). Quorum is healthy (4/4 nodes). ALL datastores are mounted and online. DLM is healthy. Memory is abundant (706 GiB free). The issue is HOST-SPECIFIC — other hosts work fine. Logs show: "File exists check timed out after 5 seconds" followed by "All heartbeat datastore paths have been unhealthy for 6 checks. Shutting down all VMs to protect data integrity".',
        'root_cause': 'After upgrade to Morpheus 9.0.1.17 with agent 3.2.6, the Morpheus agent on the affected host cannot complete heartbeat file existence/write validation within the 5-second timeout. All configured heartbeat targets are marked unhealthy for that specific host. After 6 consecutive failed checks (MAX_ISOLATION_FAIL_COUNT=6), the agent triggers protective VM shutdown. This is a false positive — the cluster, storage, and quorum are all healthy. The heartbeat timeout is host-local (possibly agent state corruption, I/O scheduling issue, or mount point stale handle after upgrade).',
        'solution': '1. IMMEDIATE: Remove affected host from workload placement / DRS\n2. Stop migrating VMs to the affected host\n3. Investigate heartbeat path on affected host: ls -la <heartbeat_mount>/hb.properties, time stat <file>\n4. Restart Morpheus agent on affected host: systemctl restart morpheus-node\n5. If agent restart does not fix: check mount health (mount | grep gfs2), check for stale NFS/GFS2 handles\n6. Verify heartbeat writes succeed before re-enabling placement\n7. Escalate to engineering if issue persists after agent restart (MORPH-13805)',
        'bug_id': 'MORPH-13805',
        'affected_versions': 'VME 9.0.1.17 with agent 3.2.6, cluster layout 1.3',
        'prevention': 'After any VME upgrade: verify heartbeat health on ALL hosts before enabling DRS. Monitor agent logs for "Unable to Write Heartbeat" on any host. Do not enable DRS until all hosts show clean heartbeat writes for at least 15 minutes.',
        'related_issues': 'MORPHL4-21 (same heartbeat mechanism, different trigger — GFS2 deadlock). Same protective shutdown logic: MvmHeartbeatFailover with MAX_ISOLATION_FAIL_COUNT=6.',
        'category': 'cluster',
        'resolution_type': 'Under investigation (MORPH-13805)',
    },
    {
        'title': 'Automation imports stale Git code repository that cannot be deleted — UI hangs on Task creation',
        'products': ['Morpheus'],
        'symptoms': 'A Git repository appears in Provisioning → Code → Repositories that cannot be deleted via UI or API. The repository URL is unreachable. Morpheus logs show repeated "remoteGitFetch transport error: cannot open git-upload-pack". When trying to add a Task under Library → Automation → Tasks, the UI hangs with a spinning wheel. Affects "Private Cloud Infrastructure Owner" and "Private Cloud Appliance Owner" roles. No API endpoint exists to list/delete code-repositories in affected version.',
        'root_cause': 'When automation (Terraform/IaC) imports a task that references a code-repository resource pointing to a non-existent Git integration URL, Morpheus creates a shell repository record in the database. This record has no corresponding entry in Administration → Integrations. The repository cannot be deleted through normal UI/API paths. When the UI attempts to load the Task creation form, it tries to fetch/validate all code repositories including the stale one, causing the UI to hang while waiting for the unreachable Git URL to timeout repeatedly.',
        'solution': "DATABASE FIX (requires MySQL access):\n1. Backup database: mysqldump -u root -p morpheus > /tmp/morpheus_backup.sql\n2. Find the stale integration: SELECT id, name, service_url FROM integration WHERE name LIKE '%<repo-name>%';\n3. Delete the integration record: DELETE FROM integration WHERE id = <id>;\n4. Verify: the New Task window should now open without hanging\n5. Prevention: ensure automation code does not reference non-existent Git repositories\n6. After fix: re-execute automation with corrected code that removes the problematic integration reference.",
        'bug_id': 'MORPH-14041',
        'affected_versions': 'Morpheus 8.0.8 (PCE-d 1.3.2), potentially all 8.x versions',
        'prevention': 'Validate Git repository URLs are reachable before importing automation tasks. Do not import code-repository resources pointing to URLs that are not accessible from the Morpheus appliance. Review IaC templates for hardcoded Git URLs before deployment.',
        'related_issues': 'MORPH-13871 (related). MORPHL4-33.',
        'category': 'application',
        'resolution_type': 'Database fix (workaround)',
    },
    {
        'title': 'VM stuck in "in shutdown" state after libvirt/QEMU teardown failure — cannot start or migrate',
        'products': ['VME', 'KVM', 'Morpheus'],
        'symptoms': 'VM cannot be powered on from Morpheus UI. virsh list shows VM in "in shutdown" state (not "shut off"). Power-on operations fail silently or with errors. Migration fails with "domain is not running". virsh domblkerror returns "End of file from qemu monitor". Logs show "Failed to terminate process <PID> with SIGKILL: Device or resource busy". VM was in this state for days until customer performed virsh destroy.',
        'root_cause': 'During a Morpheus GUI-driven shutdown workflow (virsh shutdown → sleep 10 → virsh destroy → virsh autostart --disable), the QEMU process received SIGTERM but libvirt could not complete teardown. When libvirt attempted SIGKILL, it failed with "Device or resource busy" — meaning the QEMU process was blocked in kernel-level I/O (D-state) that cannot be interrupted even by SIGKILL. The domain remained in "in shutdown" state indefinitely because libvirt domain bookkeeping was inconsistent (scope deactivated but domain runtime artifacts still referenced). LUN assignment changes ("LUN assignments on this target have changed") were observed ~10 minutes before the failure, which may have caused the underlying storage I/O stall.',
        'solution': '1. Force destroy: virsh destroy <domain>\n2. If destroy fails: check QEMU process PID and state (ps -o pid,stat -p <pid>)\n3. If process is in D-state: host reboot may be required\n4. After state is cleared: virsh start <domain>\n5. Investigate: check syslog for LUN assignment changes or storage I/O errors preceding the event\n6. Prevention: monitor for VMs in "in shutdown" state longer than 10 minutes, alert and auto-destroy if confirmed stuck.',
        'bug_id': 'MORPH-14737',
        'affected_versions': 'All VME/KVM versions (libvirt/QEMU level issue)',
        'prevention': 'Monitor VM states for domains stuck in "in shutdown" beyond 5-10 minutes. Alert on "Failed to terminate process with SIGKILL: Device or resource busy" and "End of file from qemu monitor". Investigate any LUN assignment change messages as potential precursors to VM hangs.',
        'related_issues': 'MORPHL4-26 (LUN assignment changes causing storage issues). Similar QEMU monitor EOF pattern.',
        'category': 'virtualization',
        'resolution_type': 'Operational (force destroy)',
    },
    {
        'title': 'VMs enter Unknown state after root disk fills from OpenSearch logs — large-scale migration trigger',
        'products': ['VME', 'Morpheus'],
        'symptoms': 'In large-scale environments (~750 VMs across 14 nodes, ~60 VMs/node), approximately 80 VMs enter "Unknown" state in Morpheus UI. Cluster quorum is confirmed OK. DLM reports no errors. GFS2 datastore is healthy and mounted on all nodes. virsh list --all on the host shows the VM is NOT present (not running, not defined). Member status shows "not ok" despite quorum being achieved. Issue suspected to have started when OpenSearch logs filled the root disk (/). Occurs after large-scale VM placement/migration operations (50-60 VMs simultaneously).',
        'root_cause': 'Two contributing factors identified: (1) OpenSearch/Elasticsearch logs filled the root disk partition entirely. When root disk is 100% full, critical services (libvirt, QEMU, morpheus-node agent) cannot write state files, PID files, or logs. This can cause VM domain definitions to be lost or corrupted. (2) Large-scale simultaneous VM migrations (50-60 at once) create high I/O and management plane load. Combined with full disk, some migrations may have completed at the hypervisor level but failed to properly register state back to Morpheus, leaving VMs in "Unknown" state. The VMs are not found in virsh list because they were either never properly defined on the target after migration, or their definition was lost when disk was full.',
        'solution': '1. Free disk space immediately: check df -h / on all nodes\n2. Identify the log consumer: du -sh /var/log/* | sort -rh | head\n3. If OpenSearch: truncate or rotate logs, set log retention policy\n4. For Unknown VMs: check last known host in Morpheus UI\n5. Check virsh list --all on ALL nodes (VM may be on a different host than expected)\n6. If VM found on wrong host: update Morpheus server record\n7. If VM not found anywhere: may need to recreate from backup or re-register from qcow2 disk\n8. Prevention: monitor root disk usage, set OpenSearch log rotation, limit concurrent migrations to 10-20 max.',
        'bug_id': 'MORPH-13907',
        'affected_versions': 'Morpheus 9.0.0-2 RC (large-scale environments)',
        'prevention': 'Monitor root disk usage on ALL nodes (alert at 80%). Configure OpenSearch log retention and max size. Limit concurrent VM migrations to small batches (10-20, not 50-60). Implement disk usage monitoring for /var/log specifically.',
        'related_issues': 'Disk full conditions cause cascading failures. Similar to MORPHL4-25 where /var/log filling from election storm caused extended outage.',
        'category': 'virtualization',
        'resolution_type': 'Under investigation (MORPH-13907)',
    },
    {
        'title': 'GFS2/DLM glock orphaned after lockspace recovery — QEMU process stuck in D-state indefinitely, unkillable',
        'products': ['GFS2', 'DLM', 'KVM', 'Pacemaker'],
        'symptoms': 'QEMU VM process stuck in uninterruptible sleep (D-state) with wchan=gfs2_glock_wait for 48+ hours. virsh destroy fails with "Failed to terminate process with SIGKILL: Device or resource busy". Multiple other processes (qemu-img, ls, bash) also pile up in D-state behind the same file. Cluster is quorate, all nodes online, DLM shows no errors, multipath paths all active, no SCSI/I/O errors in dmesg. GFS2 glock debug shows lock in DF (Deferred) state with all holders in W (Waiting) status — no process actually holds the lock. Issue is triggered by DLM lockspace recovery (node reboot/fencing) and a race condition in kernel DLM lock-conversion code (validate_lock_args WARN_ON at fs/dlm/lock.c).',
        'root_cause': 'During DLM lockspace recovery after a node is fenced/rebooted, there is a narrow race window between "DLM recovery done" and "GFS2 journal recovery done" where in-flight I/O (io_uring from QEMU) can race against DLM re-establishing lock ownership. This causes the DLM validate_lock_args check to fire (kernel WARN_ON), and the glock conversion request becomes orphaned — stuck in a state where no process holds it but no new holders can be granted. The stuck lock affects one specific inode (disk file) and ALL processes accessing that file pile up behind it. The trigger in this case was a libvirtd stuck-job (remoteDispatchConnectGetAllDomainStats held domain lock for ~49 hours) which delayed node shutdown past Corosync token timeout, causing unexpected STONITH fencing and forced DLM recovery.',
        'solution': '1. Identify stuck processes: ps -eo pid,stat,wchan:32,cmd | awk \'$2 ~ /^D/\'\n2. Confirm GFS2 glock wedge: cat /sys/kernel/debug/gfs2/*/glocks | grep -A5 "s:DF"\n3. Identify stuck file: find <mount> -inum <inode-from-glock>\n4. Check if any node holds the lock: lsof | grep <filename> (on all nodes)\n5. ONLY FIX: Reboot the affected node to clear the orphaned glock\n6. After reboot: verify VM starts cleanly\n7. WARNING: Rebooting may trigger the SAME bug on a different node/VM (race condition in DLM recovery)\n8. Long-term: Upgrade kernel to >=6.10+ (fix for validate_lock_args race condition)',
        'bug_id': 'MORPH-14602',
        'affected_versions': 'Kernel 6.8.0-84-generic (Ubuntu 24.04 HVM). DLM/GFS2 on any kernel <6.10.',
        'prevention': 'Upgrade kernel to 6.10+. Fix stuck libvirtd jobs (remoteDispatchConnectGetAllDomainStats) that delay shutdown and cause unexpected fencing. Always place node in standby (pcs node standby) before maintenance reboot. Monitor for D-state processes with gfs2_glock_wait wchan.',
        'related_issues': 'MORPHL4-21 (GFS2 deadlock from different trigger). Same gfs2_glock_wait D-state pattern but this one is caused by DLM recovery race, not concurrent operations.',
        'category': 'filesystem',
        'resolution_type': 'Kernel bug (fix in >=6.10)',
    },
    {
        'title': 'Host CPU/memory exhaustion causes DLM monitor timeout → fencing cascade → quorum loss → 300+ VMs down',
        'products': ['Pacemaker', 'DLM', 'GFS2', 'VME'],
        'symptoms': 'Multiple nodes fenced within 5 minutes due to DLM monitor timeout (20s). Kernel logs show "workqueue: fill_page_cache_func hogged CPU for >10000us" (escalating: 512→1024→2048 times). "High CIB load detected". OOM killer fires on one node (kills qemu-system-x86). "multipathd path checkers took longer than 42 seconds". Processes blocked in D-state (dlm_lock → gfs2_glock_nq path). After 2 nodes fenced, quorum lost with no-quorum-policy=freeze. GFS2 inaccessible. Heartbeat agent shuts down all VMs (~300+). 18 Windows VMs suffer registry corruption from abrupt power-off.',
        'root_cause': 'Two cluster nodes experienced simultaneous severe resource exhaustion (CPU starvation from fill_page_cache_func workqueue hogging + memory exhaustion triggering OOM). The resource starvation prevented DLM monitor processes from completing within the configured 20-second timeout. Since DLM is configured with on-fail=fence, Pacemaker fenced both nodes. With 2 nodes removed from an 8-node cluster (2 already in standby), only 4 active nodes remained — insufficient for quorum. no-quorum-policy=freeze stopped resource management. GFS2 became inaccessible. Heartbeat agent triggered protective VM shutdown. Windows VMs with in-flight writes suffered registry/NTFS corruption from the abrupt power-off. The resource exhaustion appears to have been triggered by rapid VM starts on the affected nodes (multiple VMs started within seconds of each other).',
        'solution': '1. Recover quorum: reboot fenced nodes, let them rejoin cluster\n2. Verify GFS2/DLM healthy: pcs status, dlm_tool status, mount | grep gfs2\n3. Start VMs gradually (NOT all at once)\n4. For corrupted Windows VMs: boot from DVD media, restore registry hive from backup\n5. Prevention: increase DLM monitor timeout from 20s to 60s\n6. Set CPU/memory reservations for host OS (ensure Pacemaker/DLM always have headroom)\n7. Stagger VM starts (do not start 10+ VMs simultaneously on one node)\n8. Monitor for "High CIB load" and "fill_page_cache_func hogged CPU" as early warnings',
        'bug_id': 'MORPH-14556',
        'affected_versions': 'All VME/Pacemaker versions with DLM on-fail=fence and 20s monitor timeout',
        'prevention': 'Increase DLM timeout to 60s. Reserve CPU/memory for host OS. Stagger VM starts. Configure Pacemaker alerts for CIB load and DLM monitor degradation. Upgrade to VME 9.x (removes Pacemaker). For Windows VMs: use VirtIO drivers + write-through caching on registry volumes.',
        'related_issues': 'MORPHL4-21 (similar heartbeat-driven VM shutdown). MORPHL4-28 (quorum loss from node failure). Windows corruption is downstream impact, not cause.',
        'category': 'cluster',
        'resolution_type': 'Configuration (increase DLM timeout, resource reservation)',
    },
    {
        'title': 'GFS2 goes read-only after host reboot due to incomplete SCSI PR registration (MORPH-5492)',
        'products': ['GFS2', 'VME', 'Pacemaker', 'Alletra'],
        'symptoms': 'After rebooting a cluster node, GFS2 mounts as read-only (ro) instead of read-write. Kernel logs show "reservation conflict" errors followed by "Error 6 writing to journal" and "about to withdraw this file system". On subsequent cluster-wide reboot: "fatal: invalid metadata block" during journal replay, GFS2 resource stuck in Starting state. Rebooting the read-only node can cause cascading VMs shutdown on OTHER nodes because the withdraw disrupts DLM lockspace recovery. mpathpersist -i -k shows fewer registered keys than expected (missing key for one iSCSI path).',
        'root_cause': 'Known bug (MORPH-5492, fixed in 8.1.0): After a host reboot, the SCSI Persistent Reservation (PR) keys are not fully re-registered on all storage paths. With only partial PR registration, writes on the unregistered path get "reservation conflict" from the storage array. GFS2 journal write fails → GFS2 withdraws → filesystem goes read-only. If the node is then rebooted while other nodes have active DLM locks referencing this journal, it can corrupt the journal metadata, causing "invalid metadata block" on next mount attempt cluster-wide.',
        'solution': '1. Before returning rebooted node to cluster: verify SCSI PR keys\n   mpathpersist -i -k /dev/mapper/<device> | grep <node-key>\n   Count should match number of active paths (typically 2 per node)\n2. If PR keys missing: manually re-register or cold reboot via ILO\n3. If GFS2 already in RO/withdrawn: put node in standby, reboot it\n4. If journal corrupted (invalid metadata block): full cluster stop → fsck.gfs2 -y → restart\n5. Upgrade to VME 8.1.0+ (contains MORPH-5492 fix)\n6. MANDATORY: always verify SCSI PR after any reboot before unstandby',
        'bug_id': 'MORPH-5492 / MORPH-14160',
        'affected_versions': 'VME 8.0.13 and earlier (fixed in 8.1.0)',
        'prevention': 'Upgrade to VME 8.1.0+. Always place node in standby (pcs node standby) before reboot. After reboot: verify mpathpersist -i -k shows correct key count BEFORE pcs node unstandby. Never reboot a node with GFS2 in RO state without first unmounting and fixing the underlying PR issue.',
        'related_issues': 'MORPHL4-28 (GFS2 corruption from power outage). MORPHL4-39. Same reservation conflict → withdraw → journal corruption chain.',
        'category': 'storage',
        'resolution_type': 'Software bug (fixed in 8.1.0)',
    },
    {
        'title': 'iSCSI connectivity degradation causes Morpheus to gracefully shutdown VMs during active I/O (MSA Gen7)',
        'products': ['VME', 'Morpheus', 'Alletra'],
        'symptoms': 'VM stops automatically after 14+ hours of continuous I/O. No guest OS crash, kernel panic, or QEMU failure — Morpheus agent initiates graceful shutdown via virsh shutdown. Preceding logs show progressive iSCSI issues: ISCSI_ERR_NOP_TIMEDOUT events, DID_TRANSPORT_DISRUPTED errors, multiple iSCSI-backed devices (sd*) becoming unavailable. LUNs not brought online automatically after snapshot restore. Issue reproducible with MSA Gen7 iSCSI but NOT with Alletra MP10000 or MSA Gen6.',
        'root_cause': 'Progressive iSCSI connectivity degradation between KVM host and MSA Gen7 storage array. The sequence: (1) Intermittent ISCSI_ERR_NOP_TIMEDOUT events indicate communication problems, (2) Sessions recover temporarily but timeouts continue, (3) Eventually DID_TRANSPORT_DISRUPTED errors cause storage path loss, (4) Multiple iSCSI-backed devices become unavailable, (5) Morpheus detects storage issue and initiates graceful VM shutdown to protect data. The shutdown is by design — Morpheus is protecting VMs from running without storage access. The underlying issue is the iSCSI connectivity instability specific to MSA Gen7 arrays.',
        'solution': '1. Check iSCSI session health: iscsiadm -m session -P 3\n2. Check for NOP timeout events in syslog: grep ISCSI_ERR_NOP /var/log/syslog\n3. Review storage array logs for the same timeframe\n4. Check multipath status: multipath -ll (look for failed/faulty paths)\n5. Validate iSCSI target network stability (ping, MTU, switch port errors)\n6. Consider increasing iSCSI NOP timeout values if timeouts are transient\n7. Check if MSA Gen7 firmware update addresses connectivity stability.',
        'bug_id': 'MORPH-14011 (cancelled — by design behavior)',
        'affected_versions': 'VME 9.0.0 with MSA Gen7 iSCSI arrays',
        'prevention': 'Monitor iSCSI session health. Alert on ISCSI_ERR_NOP_TIMEDOUT events. Review MSA Gen7 firmware for iSCSI stability fixes. Validate network infrastructure (MTU alignment, switch port health). Consider redundant iSCSI paths.',
        'related_issues': 'Similar to heartbeat-driven shutdown pattern (MORPHL4-21, MORPHL4-32) but triggered by actual storage path loss rather than false positive.',
        'category': 'storage',
        'resolution_type': 'Infrastructure (iSCSI/storage stability)',
    },
    {
        'title': 'VM creation fails with clone timeout when cluster is under sustained I/O load (iSCSI port saturation)',
        'products': ['VME', 'Alletra', 'Morpheus'],
        'symptoms': 'VM provisioning fails with timeout error after creating ~23 VMs. Subsequent single VM creation also fails. Provisioning works fine when there is no I/O load on the cluster. iSCSI port service time reaches ~275ms (high). The clone/copy operation during VM creation takes too long and exceeds the provisioning timeout. Low CPU and memory utilization on hosts — the bottleneck is storage I/O, not compute.',
        'root_cause': 'The iSCSI storage array (Alletra) has limited port count (4 ports) serving all cluster nodes. Under sustained I/O workload from existing VMs, the storage ports become saturated. When a new VM is provisioned, the disk clone operation competes with existing I/O for the same limited ports. The clone takes longer than the provisioning timeout (typically 30-60 minutes), causing the VM creation to fail. This is NOT a Morpheus/VME bug — it is a storage infrastructure capacity limitation.',
        'solution': '1. Confirm by testing: disable I/O load (stop fio/workload), try VM creation — if it works, this is the issue\n2. Fix: increase iSCSI port count on the storage array to distribute load\n3. Alternative: schedule VM provisioning during low I/O periods\n4. Workaround: reduce concurrent I/O during provisioning operations\n5. Monitor: track iSCSI port service time — alert if >100ms\n6. Consider thin provisioning to reduce clone data transfer.',
        'bug_id': 'MORPH-9626',
        'affected_versions': 'VME 8.1.2.15 with Alletra R5 (4 iSCSI ports serving 4+ nodes under load)',
        'prevention': 'Size iSCSI port count for peak load + provisioning overhead. Monitor storage port service time. Schedule batch VM creation during maintenance windows if port count is limited.',
        'related_issues': 'General storage performance issue. Not related to GFS2/DLM/cluster failures.',
        'category': 'storage',
        'resolution_type': 'Infrastructure (add iSCSI ports)',
    },
    {
        'title': 'VMs on other nodes fail after host reboot disrupts shared clustered-datastore LUN access (MSA SAS)',
        'products': ['VME', 'Morpheus', 'Alletra'],
        'symptoms': 'After rebooting one cluster host, VMs on OTHER hosts (not the rebooted one) stop and cannot boot. virsh list shows affected VMs as "shut off" on nodes that were NOT rebooted. Morpheus logs show "ensureAgentMount: failed agent mount register/remount" for shared LUN devices. Datastore refreshes timeout at ~60 seconds. Win2025 VM on an unaffected LUN remains running. Issue is storage-scoped (shared clustered datastore), not host-scoped.',
        'root_cause': 'Rebooting a SAS initiator directly attached to a shared MSA array disrupts access to clustered-datastore LUNs. On return, the rebooted node cannot re-establish multipath/mount for those LUNs (stale SCSI reservation or path loss). Because HPE Clustered Datastores are shared LUNs used cluster-wide, the disruption affects VMs whose disks reside on them regardless of which node the VMs run on. VMs on unaffected LUNs (different datastore) are not impacted.',
        'solution': '1. Check multipath state on rebooted node: multipath -ll <WWID>\n2. Check for stale SCSI reservations: sg_persist -r /dev/mapper/<WWID>\n3. If paths faulty: multipath -f <WWID> then multipath -r, or rescan SAS bus\n4. If stale PR: sg_persist --out --clear --param-rk=<key> <dev>\n5. Wait for VME to retry ensureAgentMount (warnings should stop)\n6. Verify datastore refresh completes in normal time (not 60s)\n7. Start affected VMs\n8. Prevention: put node in standby before reboot, verify LUN access after rejoin.',
        'bug_id': 'MORPH-14196',
        'affected_versions': 'VME 9.0.0 with MSA Gen6 SAS arrays (direct connect topology)',
        'prevention': 'Always put node in standby/maintenance mode before reboot. Verify multipath health and SCSI PR state after node rejoins before unstandby. Monitor ensureAgentMount failures as early warning of shared LUN access issues.',
        'related_issues': 'MORPHL4-39 (SCSI PR incomplete after reboot). Same class of issue but SAS vs iSCSI fabric.',
        'category': 'storage',
        'resolution_type': 'Operational (restore multipath/clear stale PR)',
    },
    {
        'title': 'Windows VM SQL Server extreme CPU scheduling delays — Hyper-V enlightenments missing in KVM/QEMU config',
        'products': ['VME', 'KVM'],
        'symptoms': 'Windows Server 2025 VM with SQL Server shows extreme CPU wait times (SOS_SCHEDULER_YIELD). Simple queries take 39 seconds instead of 1-2 seconds. VM has 48GB RAM but performance suggests CPU scheduling bottleneck, not memory limitation. No CPU spikes visible in monitoring. Same query runs fine on VMware, on fresh VM, or on other KVM environments. Performance degrades after VM lifecycle operations (rename, domain join, backup config).',
        'root_cause': 'Default KVM/QEMU Hyper-V enlightenment settings in Morpheus VME do not expose all the paravirtualized features that Windows/SQL Server needs for efficient CPU scheduling. Missing features: stimer direct mode, TSC/APIC frequency exposure, re-enlightenment notifications, paravirtualized TLB flush, and paravirtualized IPI. Without these, Windows falls back to less efficient timer and scheduling mechanisms, causing massive SOS_SCHEDULER_YIELD waits in SQL Server.',
        'solution': "WORKAROUND (requires virsh edit <domain>):\\n\\n1. Add Hyper-V enlightenments to VM XML:\\n   <hyperv mode='custom'>\\n     <relaxed state='on'/>\\n     <vapic state='on'/>\\n     <spinlocks state='on' retries='8191'/>\\n     <vpindex state='on'/>\\n     <runtime state='on'/>\\n     <synic state='on'/>\\n     <stimer state='on'>\\n       <direct state='on'/>\\n     </stimer>\\n     <frequencies state='on'/>\\n     <reenlightenment state='on'/>\\n     <tlbflush state='on'/>\\n     <ipi state='on'/>\\n   </hyperv>\\n\\n2. For live migration compatibility, also add TSC timer:\\n   <timer name='tsc' frequency='<host_tsc_freq>' mode='native'/>\\n   Get frequency: virsh capabilities | grep tsc\\n\\n3. Morpheus UI does not expose these settings — must use virsh edit.",
        'bug_id': 'MORPH-14550 (enhancement request)',
        'affected_versions': 'VME 8.0.13 and all versions (Morpheus does not expose advanced Hyper-V enlightenments in UI)',
        'prevention': 'For Windows VMs running SQL Server or CPU-intensive workloads: apply Hyper-V enlightenments via virsh edit after deployment. Request feature enhancement from Morpheus to expose these settings in UI.',
        'related_issues': 'Not a bug per se — enhancement request. Morpheus only exposes a subset of libvirt Hyper-V features.',
        'category': 'virtualization',
        'resolution_type': 'Configuration (virsh edit workaround)',
    },
    {
        'title': 'Morpheus shows stale 169.254.x.x (APIPA) IP on VM networking tab — causes Veeam backup failures',
        'products': ['Morpheus', 'VME'],
        'symptoms': 'Morpheus UI shows two IPs for a VM under Networking tab: the correct static IP (e.g., 172.x.x.x) and a stale APIPA address (169.254.x.x). The VM itself only has one NIC with the correct IP (confirmed via ipconfig /all and Get-NetAdapter). virsh dumpxml shows only one interface. Veeam backup fails because it sees two conflicting IPs. The stale entry persists after cloud sync, VM reconfigure, and QEMU guest agent restart.',
        'root_cause': 'Likely a bug in Morpheus cluster sync interface cleanup logic. When a VM has an interface with an IP address that is later removed (e.g., during migration from VMware, or after network reconfiguration), Morpheus retains the old address in its database (compute_server_interface / net_address tables). The cluster sync code does not properly remove addresses that no longer exist on the live VM. The APIPA address may have been briefly assigned during a network transition and captured by the QEMU guest agent before the real IP was configured.',
        'solution': "1. Confirm stale IP is NOT in the VM: ipconfig /all, Get-NetIPAddress, registry check\\n2. Try: restart QEMU Guest Agent service → trigger cloud sync → check if cleared\\n3. Try: Reconfigure VM in Morpheus (save without changes)\\n4. If still showing: database fix required:\\n   SELECT from compute_server_interface csi JOIN net_address na WHERE na.address LIKE '169.254%'\\n   DELETE the stale net_address record after confirming it matches the phantom IP\\n5. Bug: MORPH-13993 — cluster sync does not remove addresses that disappear from VM interfaces.",
        'bug_id': 'MORPH-13993',
        'affected_versions': 'VME 8.1.0 and potentially all Morpheus versions',
        'prevention': 'Ensure QEMU guest agent is installed and running before any network changes. Avoid network state transitions that create temporary APIPA addresses. For VMware-to-KVM migrations: verify Morpheus interface records match actual VM config post-migration.',
        'related_issues': 'Similar to MORPHL4-33 (stale records in Morpheus database). Affects Veeam integration when it uses Morpheus API to determine VM network config.',
        'category': 'application',
        'resolution_type': 'Database fix / Bug (MORPH-13993)',
    },
    {
        'title': 'Stale SCSI PR reservation keys from VME 8.x prevent GFS2 volumes from working in 9.x — LUNs go read-only',
        'products': ['VME', 'GFS2', 'Pacemaker'],
        'symptoms': 'After upgrading from VME 8.x to 9.x (or reusing GFS2 LUNs from a previous 8.x environment), GFS2 volumes go read-only or cannot be mounted. VMs cannot power on or access storage volumes. Cluster layout shows HVM 1.2 but hosts behave like HVM 1.3 (no Pacemaker). Agent reinstall fails with "permission denied error 13". Stale SCSI Persistent Reservation keys from the old 8.x Pacemaker/fence_scsi configuration remain on the storage LUNs, blocking write access from the 9.x environment which does not use PR.',
        'root_cause': 'VME 8.x uses Pacemaker with fence_scsi_hpevm which registers SCSI-3 Persistent Reservation (PR) keys on shared LUNs for fencing. VME 9.x (cluster layout 1.3) removes Pacemaker and does not use SCSI PR fencing. However, when LUNs are reused from 8.x without clearing the old PR registrations, the storage array still has active PR keys. Any host that does not hold a valid PR key will get "reservation conflict" on writes, causing GFS2 to go read-only or withdraw. The 9.x agents do not register PR keys (since they do not use Pacemaker), so ALL writes fail.',
        'solution': '1. Identify all GFS2 LUNs: blkid | grep gfs2\n2. Check existing PR keys: mpathpersist -i -k /dev/mapper/<device>\n3. If keys exist from old 8.x environment: clear ALL PR registrations\n4. Clear from a registered host: mpathpersist --out --clear --param-rk=<key> /dev/mapper/<device>\n5. If no host can clear (no valid key): use sg_persist on individual paths:\n   sg_persist --out --register --param-rk=0x0 --param-sark=<temp_key> /dev/<path>\n   sg_persist --out --clear --param-rk=<temp_key> /dev/<path>\n6. Verify: mpathpersist -i -k /dev/mapper/<device> (should show no keys)\n7. Remount GFS2 and verify RW access',
        'bug_id': 'MORPH-14198',
        'affected_versions': 'VME 9.x when reusing LUNs from VME 8.x environments (any version with Pacemaker/fence_scsi)',
        'prevention': 'Before reusing LUNs from VME 8.x in 9.x: clear ALL SCSI PR keys from every LUN. Document PR key cleanup as mandatory step in 8.x→9.x upgrade procedure. Do not assume LUNs are clean just because Pacemaker is removed.',
        'related_issues': 'MORPHL4-46 (same issue in reverse — PR keys blocking 9.x). MORPHL4-39 (PR incomplete after reboot). MORPH-5492.',
        'category': 'storage',
        'resolution_type': 'Operational (clear stale PR keys)',
    },
    {
        'title': 'VM memory and storage metrics not reported without Morpheus Agent — virtual appliances cannot be monitored',
        'products': ['Morpheus', 'VME'],
        'symptoms': 'VM shows CPU, Network, and Disk I/O (IOPS) metrics in Morpheus UI but Memory (RAM) and Storage utilization are blank/missing. Affects vendor-supplied virtual appliances (Qualys, OneView, OpsRamp Gateway) where Morpheus Agent cannot be installed. Customer cannot determine if a VM is running out of memory or storage.',
        'root_cause': 'By design, Morpheus requires the Morpheus Agent installed inside the guest OS to report Memory and Storage metrics. Without the agent, only hypervisor-level metrics are available (CPU via libvirt stats, Network TX/RX via tap device stats, basic Disk I/O). Memory utilization requires guest cooperation (balloon driver or agent) because the hypervisor cannot distinguish between allocated-but-unused and actively-used memory inside the guest. Storage utilization requires filesystem-level visibility that only an in-guest agent can provide.',
        'solution': "1. If agent can be installed: install Morpheus Agent → memory and storage will report\\n2. If agent CANNOT be installed (hardened appliance):\\n   - CPU, Network, IOPS still visible from hypervisor\\n   - Memory: use QEMU guest agent (qemu-ga) if available — some vendors include it\\n   - Storage: not available without in-guest agent or QEMU guest agent\\n   - Alternative: use OpsRamp or external monitoring (SNMP, agentless) for these VMs\\n3. Note: network stats are in bytes/sec (not bits/sec)\\n4. Note: CPU graph data is averaged over wider time windows (97% in 24h view = ~50% in 1-week view due to downsampling)",
        'bug_id': 'MORPH-14621 (enhancement request)',
        'affected_versions': 'All Morpheus/VME versions (by design limitation)',
        'prevention': 'Document which VM types require external monitoring. For vendor appliances that support QEMU guest agent but not Morpheus agent, enable qemu-ga for basic memory reporting. Plan monitoring strategy that does not solely rely on Morpheus for appliance VMs.',
        'related_issues': 'MORPH-7272 (network stats not displaying in cluster view). Product limitation, not a bug.',
        'category': 'application',
        'resolution_type': 'Product limitation (enhancement requested)',
    },
    {
        'title': 'HVM 9.0 installer (S5Q83-11078) crashes during SAN boot with multipath — Ubuntu subiquity regression',
        'products': ['VME'],
        'symptoms': 'HVM 9.0 OS installation fails during "configure multipath" phase when boot LUN is presented over multiple FC/SAS paths (SAN boot). Installer hangs or crashes with Python exception in subiquity. Same hardware + same config works fine with HVM 8.1.2 installer (S5Q83-11056). Issue reproduces on Synergy Gen12, Gen11, and ProLiant DL380 Gen11. Local disk installation works fine. Single-path installation succeeds but enabling additional paths post-install causes reboot loop.',
        'root_cause': 'Ubuntu 24.04.4 subiquity installer has a regression in its curtin storage backend. When the installer encounters a SAN boot LUN across multiple active FC paths, curtin crashes during multipath configuration due to a race condition between multipathd path scanning and LVM volume group creation. Additionally, when installing with single path, the installer writes /boot references as raw device paths (/dev/sda2) instead of multipath device paths, and hardcodes GRUB hardware hints (hd0,gpt2). This breaks boot when additional paths are enabled.',
        'solution': "WORKAROUND (install with single path, then fix):\\n1. Reduce to SINGLE FC path in OneView/Virtual Connect profile\\n2. Install HVM 9.0 with single path (will succeed)\\n3. After install, FIX multipath config:\\n   - Add boot LUN WWID to /etc/multipath/wwids\\n   - Set user_friendly_names=no in /etc/multipath.conf\\n   - Update /etc/fstab: change /dev/disk/by-uuid/ to /dev/disk/by-id/dm-uuid-part*-mpath-<WWID>\\n   - Update /etc/default/grub: add iommu=pt intel_iommu=on\\n   - Run: update-grub && update-initramfs -u -k all\\n   - Remove GRUB hardware hints (--hint-bios, --hint-efi)\\n4. Reboot with single path to verify\\n5. Re-enable all FC paths in OneView\\n6. Verify: multipath -ll shows all paths active\\n\\nALTERNATIVE: Install HVM 8.1.2 first, then upgrade to 9.0.",
        'bug_id': 'Ubuntu subiquity/curtin regression (no MORPH ticket — OS-level issue)',
        'affected_versions': 'HVM 9.0 installer (HPE_HVM_Install_24.04_S5Q83-11078). Also stock Ubuntu 24.04 installer.',
        'prevention': 'Use HVM 8.1.2 installer for SAN boot environments, then upgrade. Or use single-path install + post-fix procedure. Issue is in Ubuntu installer, not HPE-specific.',
        'related_issues': 'Ubuntu community reports same issue on Cisco UCS M480 with FC SAN. Not HPE-specific bug.',
        'category': 'system',
        'resolution_type': 'OS-level bug (workaround available)',
    },
    {
        'title': 'VMware to VME migration drops Secure Boot — migrated VMs boot UEFI but Secure Boot unsupported',
        'products': ['VME', 'Morpheus'],
        'symptoms': 'VMs migrated from VMware using Bulk Migration tool always have Secure Boot disabled on destination. Source VM has Secure Boot enabled in vCenter. Migration completes successfully with no errors. Destination VM boots in UEFI mode but guest OS reports "Secure Boot State: Unsupported". VMs deployed fresh in same VME environment have Secure Boot working correctly. Database shows source compute_server.secure_boot=0x01 but destination compute_server.secure_boot=0x00 or NULL.',
        'root_cause': 'Product defect in the Morpheus migration workflow (MigrationPlanService). During VMware → VME migration, the instance config payload includes uefi:true but does NOT propagate the secure_boot attribute from the source VM. KvmProvisionService.groovy defaults secureBoot=false when the attribute is absent from the config. The source VMs secure_boot value (read via VmwareComputeService from vCenter) is not passed through the migration create payload to KvmComputeUtility.',
        'solution': "WORKAROUND (post-migration):\\n1. Shut down the migrated VM\\n2. Edit VM XML: virsh edit <domain>\\n3. Find the <os> section and ensure it has:\\n   <os firmware='efi'>\\n     <firmware>\\n       <feature enabled='yes' name='secure-boot'/>\\n     </firmware>\\n   </os>\\n4. Or add: <loader readonly='yes' secure='yes' type='pflash'>/usr/share/OVMF/OVMF_CODE_4M.secboot.fd</loader>\\n5. Save and start VM\\n6. Verify in guest: Confirm-SecureBootUEFI (PowerShell) or msinfo32\\n\\nPermanent fix: awaiting engineering fix (MORPH-14756).",
        'bug_id': 'MORPH-14756',
        'affected_versions': 'VME 8.1.2 and 9.0.0 (Bulk Migration tool)',
        'prevention': 'After any VMware → VME migration: verify Secure Boot status in guest OS. If missing, apply virsh edit workaround. Track MORPH-14756 for permanent fix.',
        'related_issues': 'MORPHL4-49. Similar to MORPH-14550 (Hyper-V enlightenments not propagated) — pattern of VM attributes not being preserved during migration/provisioning.',
        'category': 'virtualization',
        'resolution_type': 'Software bug (MORPH-14756)',
    },
    {
        'title': 'Quorum section missing from GUI after VME 9.0.0-2 + HVM 1.3 layout upgrade — cluster is actually healthy',
        'products': ['VME', 'Morpheus'],
        'symptoms': 'After upgrading VME to 9.0.0-2 and performing HVM 1.3 cluster layout upgrade, the Quorum section disappears from the cluster summary page in the Morpheus GUI. Logs show "No online hosts found for quorum status refresh" after every datastore refresh cycle. However, the cluster is actually healthy: all nodes online, Corosync quorate, DLM working, GFS2 mounted RW, VMs running normally. morpheus-ui restart does not fix it.',
        'root_cause': 'Display/workflow issue in the VME 9.0.0-2 quorum status refresh logic after HVM Cluster Layout 1.3 upgrade. The 1.3 layout upgrade transfers HA ownership from Pacemaker to the Morpheus Agent (QuorumCheckService). The quorum-status refresh job fails a host-eligibility check post-upgrade despite all hosts being fully online and healthy. The refresh code cannot find "eligible" hosts for quorum polling, even though cluster discovery, host discovery, Pacemaker status caching, and inventory refresh all work correctly.',
        'solution': '1. IMPORTANT: The cluster IS healthy — this is a display-only issue\n2. Verify cluster health independently: pcs status, corosync-quorum-tool, dlm_tool ls\n3. Do NOT take corrective action on the cluster itself\n4. Wait for engineering fix (this is a post-upgrade refresh workflow bug)\n5. morpheus-ui restart does not resolve the issue\n6. The quorum section should reappear once the eligibility check logic is fixed.',
        'bug_id': 'MORPHL4-50 (under investigation)',
        'affected_versions': 'VME 9.0.0-2 after HVM Cluster Layout 1.2 → 1.3 upgrade',
        'prevention': 'Known post-upgrade cosmetic issue. Verify cluster health via CLI (pcs status, corosync-quorum-tool) rather than relying solely on GUI quorum display after upgrade.',
        'related_issues': 'Related to HVM 1.3 architecture change (removes Pacemaker dependency, introduces agent-based quorum). MORPHL4-28 discussion of 9.x architectural changes.',
        'category': 'application',
        'resolution_type': 'Display bug (under investigation)',
    },
]
