"""Known issues database for LogSherlock Pro.

Contains 25+ pre-loaded known issues covering HPE products:
Morpheus, KVM, Alletra, GFS2, VME, Pacemaker.
"""

KNOWN_ISSUES = [
    {
        'title': 'GFS2 withdraw due to SCSI reservation conflict on shared LUN',
        'products': ['GFS2', 'Alletra'],
        'symptoms': 'GFS2 filesystem withdraw; SCSI reservation conflict in dmesg; I/O errors on shared device',
        'root_cause': 'When two cluster nodes simultaneously attempt I/O on a shared LUN without proper SCSI-3 PR coordination, reservation conflicts occur causing GFS2 to withdraw to protect data integrity.',
        'solution': '1. Verify SCSI-3 PR registrations (sg_persist --in -k /dev/mapper/mpathX)\n2. Check fencing agent configuration\n3. Restart DLM and GFS2 on affected node\n4. If persistent, check storage array for LUN masking issues',
        'bug_id': 'BZ-2024-1847',
        'affected_versions': 'RHEL 8.6-8.8, GFS2 all versions with Alletra 9000 series',
    },
    {
        'title': 'Morpheus provisioning fails with libvirt connection timeout',
        'products': ['Morpheus', 'KVM'],
        'symptoms': 'Instance creation fails; libvirt connection refused or timeout; morpheus-ui logs show "Failed to connect to hypervisor"',
        'root_cause': 'Morpheus worker connection pool exhaustion when multiple concurrent provisions are requested. The libvirtd socket accepts limited connections and morpheus does not gracefully handle pool exhaustion.',
        'solution': '1. Restart morpheus-ui service\n2. Increase libvirtd max_clients in /etc/libvirt/libvirtd.conf (default 5000)\n3. Check morpheus worker count vs hypervisor capacity\n4. Apply Morpheus patch 6.2.1-hotfix-3',
        'bug_id': 'MORPH-2024-0892',
        'affected_versions': 'Morpheus 6.0.x - 6.2.0',
    },
    {
        'title': 'KVM VM fails to start after host reboot - AppArmor denial',
        'products': ['KVM'],
        'symptoms': 'VM start fails with "Permission denied"; AppArmor denial in audit.log; domain XML references moved disk path',
        'root_cause': 'After host reboot, AppArmor profile for libvirt does not include dynamically added disk paths. If disk images were moved or new paths added without updating AppArmor, VMs cannot access their disks.',
        'solution': '1. Check /var/log/audit/audit.log for AppArmor denials\n2. Add disk path to /etc/apparmor.d/abstractions/libvirt-qemu\n3. Reload AppArmor: apparmor_parser -r /etc/apparmor.d/libvirt/TEMPLATE.qemu\n4. Or set security_driver = "none" in /etc/libvirt/qemu.conf (less secure)',
        'bug_id': 'KVM-2023-0445',
        'affected_versions': 'Ubuntu 20.04+, All KVM versions with AppArmor',
    },
    {
        'title': 'Alletra multipath failover causes 120-second I/O pause',
        'products': ['Alletra'],
        'symptoms': 'I/O hangs for 120 seconds during path failover; multipath shows paths switching; applications report timeout',
        'root_cause': 'Default SCSI timeout (30s) combined with multipath retry count (4) creates 120-second total timeout before failover completes. The dev_loss_tmo and fast_io_fail_tmo are not optimally configured for Alletra arrays.',
        'solution': '1. Set dev_loss_tmo=30 in multipath.conf for Alletra devices\n2. Set fast_io_fail_tmo=5\n3. Set no_path_retry=5\n4. Rebuild initramfs and reboot\n5. Verify with: multipathd show config local',
        'bug_id': 'ALT-2024-0156',
        'affected_versions': 'Alletra 6000/9000, All OS versions with default multipath settings',
    },
    {
        'title': 'Pacemaker fence race condition causes both nodes to reboot',
        'products': ['Pacemaker'],
        'symptoms': 'Both cluster nodes reboot simultaneously; fence history shows mutual fencing; split-brain detected',
        'root_cause': 'When corosync communication fails symmetrically (switch failure), both nodes lose contact simultaneously. Without proper quorum configuration, both nodes attempt to fence each other, causing a dual reboot.',
        'solution': '1. Configure proper quorum device (qdevice/qnetd)\n2. Set no-quorum-policy=suicide for 2-node clusters\n3. Use priority fencing with proper delay on one node\n4. Add fence_delay=5 to secondary node fence config',
        'bug_id': 'PCS-2024-0234',
        'affected_versions': 'Pacemaker 2.0.x - 2.1.x, 2-node cluster configurations',
    },
    {
        'title': 'GFS2 lock contention causes cluster-wide hang',
        'products': ['GFS2', 'Pacemaker'],
        'symptoms': 'All nodes accessing GFS2 become unresponsive; DLM lock waits > 60 seconds; processes in D state',
        'root_cause': 'Heavy small-file workload on GFS2 creates excessive DLM lock traffic. When lock requests exceed cluster network capacity, all nodes enter a deadlock-like state waiting for lock grants.',
        'solution': '1. Reduce concurrent file operations on GFS2\n2. Use local filesystem for temp/work directories\n3. Tune gfs2 lock_dlm parameters: mount -o noatime,nodiratime\n4. Increase corosync token timeout to prevent false fencing\n5. Consider using NFS exports from one node instead of direct GFS2 access from all',
        'bug_id': 'GFS2-2024-0078',
        'affected_versions': 'GFS2 on RHEL 8.x/9.x with > 4 nodes',
    },
    {
        'title': 'VME backup fails with snapshot creation timeout',
        'products': ['VME', 'KVM'],
        'symptoms': 'VME backup job fails; "snapshot creation timeout" in VME logs; qemu-img process stuck',
        'root_cause': 'VME snapshot creation uses qemu-guest-agent freeze/thaw. If the guest agent is not installed or unresponsive, the snapshot times out after 60 seconds and the backup fails.',
        'solution': '1. Verify qemu-guest-agent is installed and running in the VM\n2. Check guest agent socket: virsh qemu-agent-command <domain> \'{"execute":"guest-ping"}\'\n3. Increase VME snapshot timeout in config\n4. For Linux VMs, ensure qemu-ga service is enabled',
        'bug_id': 'VME-2024-0112',
        'affected_versions': 'VME 7.x with KVM hypervisors',
    },
    {
        'title': 'SMAD agent memory leak causes OOM kill',
        'products': ['Morpheus'],
        'symptoms': 'SMAD memory usage grows over days; eventually OOM killed; monitoring gaps after restart',
        'root_cause': 'SMAD agent leaks memory when processing metrics from VMs with frequently changing disk configurations. Each disk change event allocates monitoring structures that are never freed.',
        'solution': '1. Update SMAD to version 4.2.1+ (includes fix)\n2. Workaround: Schedule weekly SMAD restart via cron\n3. Set memory limit in systemd: MemoryMax=512M in smad.service\n4. Reduce metric collection frequency in smad.conf',
        'bug_id': 'SMAD-2024-0067',
        'affected_versions': 'SMAD 4.0.0 - 4.2.0',
    },
    {
        'title': 'Corosync token timeout causes unnecessary fencing',
        'products': ['Pacemaker'],
        'symptoms': 'Nodes fenced during high CPU load; corosync token timeouts in logs; system load > 50',
        'root_cause': 'Under heavy CPU load, corosync cannot process heartbeat tokens within the default timeout (1000ms). The cluster incorrectly assumes the node is dead and fences it.',
        'solution': '1. Increase corosync token timeout: token: 5000 in corosync.conf\n2. Set consensus: 7500 (1.2x token + token)\n3. Set corosync process to real-time priority\n4. Investigate root cause of high CPU load',
        'bug_id': 'COR-2023-0189',
        'affected_versions': 'Corosync 2.x/3.x with default token timeout',
    },
    {
        'title': 'Morpheus instance stuck in provisioning state',
        'products': ['Morpheus'],
        'symptoms': 'Instance shows "Provisioning" indefinitely; cloud-init completed; Morpheus agent installed but not reporting',
        'root_cause': 'Morpheus agent requires outbound HTTPS (443) to the Morpheus appliance. If firewall rules block this after VM provisioning, the agent cannot report completion and the instance stays in provisioning state.',
        'solution': '1. Verify network connectivity from VM to Morpheus appliance on port 443\n2. Check VM firewall rules (iptables/nftables)\n3. Verify Morpheus agent is running: systemctl status morpheus-node-agent\n4. Manually complete provisioning via API if network issue is resolved',
        'bug_id': 'MORPH-2024-0445',
        'affected_versions': 'Morpheus 5.x - 6.x',
    },
    {
        'title': 'Alletra volume offline after array controller failover',
        'products': ['Alletra'],
        'symptoms': 'LUNs go offline after controller failover; multipath shows all paths failed; applications lose access',
        'root_cause': 'During Alletra controller failover, LUN ownership transfers between controllers. If the host ALUA settings are incorrect, the host does not follow the LUN to the new controller path.',
        'solution': '1. Verify ALUA is enabled: sg_rtpg /dev/sdX\n2. Check multipath.conf has correct Alletra settings (path_grouping_policy=group_by_prio)\n3. Set prio=alua in multipath.conf\n4. Rescan SCSI: echo "- - -" > /sys/class/scsi_host/host*/scan',
        'bug_id': 'ALT-2024-0203',
        'affected_versions': 'Alletra 9000 with firmware < 9.4.1',
    },
    {
        'title': 'KVM live migration fails with "migration was active" error',
        'products': ['KVM', 'Morpheus'],
        'symptoms': 'Live migration fails; "migration was active" error; VM stays on source; destination cleanup required',
        'root_cause': 'A previous failed migration left stale state on the destination. Libvirt does not clean up properly when migration is interrupted, leaving the destination thinking a migration is in progress.',
        'solution': '1. On destination: virsh list --all (find the stale domain)\n2. virsh destroy <domain> on destination\n3. virsh undefine <domain> on destination\n4. Retry migration\n5. If persistent, restart libvirtd on destination',
        'bug_id': 'KVM-2024-0201',
        'affected_versions': 'libvirt 8.x - 9.x',
    },
    {
        'title': 'GFS2 fsck required after unclean shutdown',
        'products': ['GFS2'],
        'symptoms': 'GFS2 mount fails after power outage; "journal recovery failed"; filesystem marked dirty',
        'root_cause': 'After unclean shutdown (power loss, kernel panic), GFS2 journal replay may fail if the journal contains references to blocks that were being written during the crash.',
        'solution': '1. Try mounting with -o errors=continue to attempt journal replay\n2. If that fails, run fsck.gfs2 -y /dev/mapper/<vg>-<lv>\n3. After fsck, attempt mount again\n4. Verify data integrity after recovery\n5. Implement UPS and proper shutdown procedures',
        'bug_id': 'GFS2-2023-0445',
        'affected_versions': 'All GFS2 versions',
    },
    {
        'title': 'Pacemaker resource agent timeout during storage failover',
        'products': ['Pacemaker', 'Alletra'],
        'symptoms': 'Resource monitor timeout; pacemaker marks resource as failed; unnecessary failover triggered',
        'root_cause': 'Default resource monitor timeout (20s) is too short when storage is experiencing a path failover (which can take up to 120s with default multipath settings).',
        'solution': '1. Increase resource monitor timeout: pcs resource op update <resource> monitor timeout=180s\n2. Fix underlying multipath timeout (see Alletra multipath failover issue)\n3. Configure resource migration-threshold to tolerate brief failures',
        'bug_id': 'PCS-2024-0301',
        'affected_versions': 'Pacemaker 2.x with default resource timeouts',
    },
    {
        'title': 'VME incremental backup chain broken',
        'products': ['VME'],
        'symptoms': 'Incremental backup fails; "parent snapshot not found"; requires full backup to resume',
        'root_cause': 'When a VM snapshot is manually deleted or the VM is restored to a previous snapshot, the VME incremental backup chain is broken because the reference point no longer exists.',
        'solution': '1. Delete the broken backup chain in VME console\n2. Create a new full backup as the new base\n3. Avoid manually deleting snapshots that VME is tracking\n4. Configure VME retention to clean up old chains automatically',
        'bug_id': 'VME-2024-0089',
        'affected_versions': 'VME 6.x - 7.x',
    },
    {
        'title': 'Morpheus agent fails to install on RHEL 9 with FIPS enabled',
        'products': ['Morpheus'],
        'symptoms': 'Agent install script fails; SSL handshake error; FIPS mode blocks certain ciphers',
        'root_cause': 'Morpheus agent installer uses TLS ciphers that are not FIPS-compliant. When FIPS mode is enabled on RHEL 9, the SSL handshake fails during agent download.',
        'solution': '1. Update Morpheus appliance to 6.2.2+ (includes FIPS-compatible ciphers)\n2. Workaround: Manually download agent package and install offline\n3. Or temporarily add TLS 1.2 FIPS cipher to Morpheus nginx config',
        'bug_id': 'MORPH-2024-0678',
        'affected_versions': 'Morpheus 6.0.x - 6.2.1 with RHEL 9 FIPS mode',
    },
    {
        'title': 'Kernel OOM kills critical cluster processes',
        'products': ['Pacemaker', 'GFS2'],
        'symptoms': 'corosync or dlm_controld OOM killed; cluster loses quorum; GFS2 withdraws',
        'root_cause': 'Memory pressure from application workloads causes OOM killer to target cluster daemons. Default OOM score adjustment does not protect corosync/pacemaker adequately.',
        'solution': '1. Set OOM score adjust for critical processes: echo -1000 > /proc/$(pidof corosync)/oom_score_adj\n2. Add OOMScoreAdjust=-1000 to corosync.service and pacemaker.service\n3. Configure proper memory limits for application workloads\n4. Add swap space as a buffer',
        'bug_id': 'PCS-2023-0556',
        'affected_versions': 'All cluster versions on memory-constrained systems',
    },
    {
        'title': 'Alletra iSCSI login storm after network flap',
        'products': ['Alletra'],
        'symptoms': 'Hundreds of iSCSI login attempts; iscsid log filled with retries; brief network outage causes extended recovery',
        'root_cause': 'After a network flap, all iSCSI sessions attempt to reconnect simultaneously. The Alletra array rate-limits logins, causing cascading timeouts and extended recovery time.',
        'solution': '1. Configure node.session.timeo.replacement_timeout=30 in iscsid.conf\n2. Stagger session recovery with random delay\n3. Use multiple portals to distribute login load\n4. Configure Alletra to increase login queue depth',
        'bug_id': 'ALT-2024-0089',
        'affected_versions': 'Alletra 6000/9000 with iSCSI, > 32 sessions per host',
    },
    {
        'title': 'KVM nested virtualization crash with AMD EPYC',
        'products': ['KVM'],
        'symptoms': 'Guest kernel panic during nested VM boot; "KVM: entry failed" in host dmesg; AVIC-related errors',
        'root_cause': 'AMD AVIC (Advanced Virtual Interrupt Controller) conflicts with nested virtualization on EPYC 7003 series processors with certain firmware versions.',
        'solution': '1. Disable AVIC: echo "options kvm-amd avic=0" > /etc/modprobe.d/kvm-nested.conf\n2. Reload KVM module: modprobe -r kvm-amd && modprobe kvm-amd\n3. Or update host BIOS/firmware to latest version\n4. Verify with: cat /sys/module/kvm_amd/parameters/avic',
        'bug_id': 'KVM-2024-0334',
        'affected_versions': 'AMD EPYC 7003 series, kernel 5.15-6.1',
    },
    {
        'title': 'GFS2 performance degradation with many small files',
        'products': ['GFS2'],
        'symptoms': 'ls/stat operations take > 5 seconds; DLM lock count > 1M; cluster network saturated with lock traffic',
        'root_cause': 'GFS2 requires a DLM lock per inode. Directories with thousands of small files generate massive lock traffic across the cluster interconnect, causing performance degradation for all nodes.',
        'solution': '1. Restructure workload to use fewer, larger files\n2. Use local filesystem (ext4/xfs) for temporary/working data\n3. Reduce number of GFS2-accessing nodes\n4. Mount with noatime,nodiratime to reduce lock operations\n5. Consider NFS from single node for read-heavy workloads',
        'bug_id': 'GFS2-2024-0134',
        'affected_versions': 'All GFS2 versions with > 100K files per directory',
    },
    {
        'title': 'Morpheus workflow execution stalls after database connection pool exhaustion',
        'products': ['Morpheus'],
        'symptoms': 'Workflows stuck in running state; database pool exhaustion errors in morpheus-ui.log; all API calls slow',
        'root_cause': 'Long-running workflows hold database connections. When multiple workflows run concurrently, the connection pool is exhausted, blocking all other operations including health checks.',
        'solution': '1. Increase max pool size in morpheus.rb: db.pool.max=100\n2. Set connection timeout: db.pool.timeout=30000\n3. Identify and optimize long-running workflows\n4. Restart morpheus-ui to release stuck connections\n5. Monitor with: morpheus-ctl db-pool-status',
        'bug_id': 'MORPH-2024-0234',
        'affected_versions': 'Morpheus 6.x with default pool settings',
    },
    {
        'title': 'VME restore fails due to changed storage pool',
        'products': ['VME', 'KVM'],
        'symptoms': 'VM restore fails; "storage pool not found" error; backup metadata references deleted pool',
        'root_cause': 'VME stores the original storage pool UUID in backup metadata. If the pool was recreated or renamed after backup, the restore cannot find the target location.',
        'solution': '1. Create a storage pool with the same name as original\n2. Or use VME CLI to override restore target: vme restore --target-pool <new-pool>\n3. Edit backup metadata XML to update pool reference\n4. Verify target pool has sufficient space before restore',
        'bug_id': 'VME-2023-0567',
        'affected_versions': 'VME 6.x - 7.x',
    },
    {
        'title': 'Pacemaker constraint conflict prevents resource start',
        'products': ['Pacemaker'],
        'symptoms': 'Resource in Stopped state; "unmanaged" or "blocked" in pcs status; constraint violations in logs',
        'root_cause': 'Conflicting location constraints or colocation rules prevent the cluster from finding a valid node to start the resource. Often caused by accumulated ban constraints from previous failures.',
        'solution': '1. Check constraints: pcs constraint show --full\n2. Remove stale ban constraints: pcs resource clear <resource>\n3. Review location constraints for conflicts\n4. Check resource-stickiness and migration-threshold settings\n5. pcs resource cleanup <resource> to clear failure counts',
        'bug_id': 'PCS-2024-0167',
        'affected_versions': 'Pacemaker 2.x',
    },
    {
        'title': 'SMAD fails to monitor VMs after libvirtd restart',
        'products': ['Morpheus', 'KVM'],
        'symptoms': 'SMAD shows VMs as offline; monitoring gaps; libvirt connection "reset by peer" in SMAD logs',
        'root_cause': 'SMAD caches libvirt connection handles. When libvirtd is restarted, cached connections become invalid but SMAD does not reconnect until its own restart.',
        'solution': '1. Restart SMAD: systemctl restart smad\n2. Apply SMAD 4.2.2+ which includes connection recovery\n3. Monitor SMAD health after any libvirtd maintenance\n4. Add systemd dependency: After=libvirtd.service in smad.service',
        'bug_id': 'SMAD-2024-0112',
        'affected_versions': 'SMAD 4.0.x - 4.2.1',
    },
    {
        'title': 'Network bond failover causes ARP cache poisoning',
        'products': ['KVM', 'Pacemaker'],
        'symptoms': 'Network connectivity lost after bond failover; upstream switch shows wrong MAC; gratuitous ARP not received',
        'root_cause': 'When a bond fails over to the backup NIC, gratuitous ARP packets are sent to update upstream switch MAC tables. If the switch ARP timeout is long or gratuitous ARP is filtered, connectivity is lost until the switch cache expires.',
        'solution': '1. Configure bond with arp_interval=100 and arp_validate=all\n2. Verify switch accepts gratuitous ARP\n3. Set bond updelay=200 to stabilize before sending traffic\n4. For mode=1, set primary_reselect=better\n5. Manually clear ARP on switch if urgent: clear arp-cache',
        'bug_id': 'NET-2024-0078',
        'affected_versions': 'All Linux bonding versions with layer-2 switches',
    },
    {
        'title': 'Alletra deduplication causes latency spikes during garbage collection',
        'products': ['Alletra'],
        'symptoms': 'Periodic latency spikes every 4-6 hours; I/O latency > 100ms during spikes; array "gc" process active',
        'root_cause': 'Alletra deduplication garbage collection runs periodically to reclaim space from deleted deduplicated blocks. On heavily utilized arrays, this process competes with production I/O.',
        'solution': '1. Schedule GC during low-I/O windows via array management\n2. Increase GC throttle setting on the Alletra array\n3. If latency is unacceptable, consider disabling dedup for latency-sensitive volumes\n4. Ensure array is not > 80% capacity (GC becomes more aggressive)',
        'bug_id': 'ALT-2024-0345',
        'affected_versions': 'Alletra 9000 with deduplication enabled, capacity > 70%',
    },
    {
        'title': 'iptables rules lost after HVM host reboot - missing iptables-persistent',
        'products': ['Morpheus', 'HVM'],
        'symptoms': 'After server reboot, iptables rules are gone. Servers cannot communicate. Cluster loses quorum. Ports 443, 9200, 9300, 5672, 3306 become unreachable between nodes. Self-fencing risk.',
        'root_cause': 'iptables-persistent package not installed on Ubuntu/Debian HVM hosts. iptables rules are held in memory only and flushed on reboot. Morpheus 9.0.x installer does not install iptables-persistent as prerequisite.',
        'solution': '1. Install iptables-persistent: apt-get install iptables-persistent\n2. Save current rules: iptables-save > /etc/iptables/rules.v4\n3. Enable service: systemctl enable netfilter-persistent\n4. Reboot and verify: iptables -L -n\n\nApply to ALL HVM hosts in rolling fashion (one at a time to maintain quorum).',
        'bug_id': 'MORPHL4-77',
        'affected_versions': 'Morpheus Enterprise 9.0.0-2, 9.0.x on Ubuntu/Debian HVM hosts',
        'prevention': 'Add iptables-persistent to Morpheus HVM host setup prerequisites. Add post-reboot health check script. Include in pre-upgrade checklist.',
        'related_issues': 'Netplan apply required on hosts 02/04/06 after reboot (possible Aruba CX plugin residual). Self-fencing risk if multiple nodes reboot simultaneously.',
        'category': 'network',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'Netplan apply required after reboot for storage access',
        'products': ['Morpheus', 'HVM', 'Network'],
        'symptoms': 'After server reboot, storage network not accessible. Hosts require manual netplan apply to restore storage connectivity. Only affects specific hosts (not all).',
        'root_cause': 'Possible residual network configuration from previously used Aruba CX plugin. Netplan configuration may have ordering/dependency issue that prevents automatic application on boot.',
        'solution': '1. Check /etc/netplan/*.yaml for correct config\n2. Run netplan apply on affected hosts\n3. Remove any residual Aruba CX plugin config\n4. Verify with: ip addr show and ping storage targets\n5. Consider adding netplan apply to post-boot script as temporary workaround.',
        'bug_id': 'MORPHL4-77 (secondary)',
        'affected_versions': 'Morpheus 9.0.x with previous Aruba CX plugin usage',
        'prevention': 'Clean removal procedure for Aruba CX plugin. Verify netplan configs after plugin removal.',
        'related_issues': 'Related to iptables-persistent issue. Both occur post-reboot.',
        'category': 'network',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'VMDK deployment fails on Alletra vVOL Datastore',
        'products': ['Alletra', 'Morpheus', 'Storage'],
        'symptoms': 'Unable to deploy a VMDK to an Alletra vVOL (Virtual Volume) Datastore. Deployment fails with storage error.',
        'root_cause': 'VASA provider connectivity issue, protocol endpoint not accessible, or vVOL datastore not properly configured for VMDK format.',
        'solution': '1. Verify VASA provider is registered and healthy\n2. Check Alletra array connectivity\n3. Verify protocol endpoints are accessible from all hosts\n4. Check VMDK compatibility with vVOL datastore type\n5. Review Morpheus datastore configuration.',
        'bug_id': 'MORPHL4-84',
        'affected_versions': 'Morpheus with Alletra vVOL integration',
        'prevention': 'Verify vVOL datastore compatibility before VMDK deployment. Monitor VASA provider health.',
        'related_issues': 'May relate to Alletra array replication or protocol endpoint issues.',
        'category': 'storage',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'Cluster self-fencing in 2-node VME environment with external worker',
        'products': ['VME', 'Pacemaker', 'Corosync'],
        'symptoms': 'Cluster self-fencing occurs in VME 9.0.0_2 with 2-node setup and external worker. Nodes fence each other unexpectedly.',
        'root_cause': 'In 2-node clusters, quorum calculation is sensitive. If communication between nodes fails (even briefly), both nodes may attempt to fence the other. External worker node may not properly participate in quorum voting.',
        'solution': '1. Verify corosync communication between all nodes\n2. Check two_node: 1 setting in corosync.conf\n3. Verify external worker quorum participation\n4. Review fence device configuration\n5. Check network stability between nodes\n6. Consider wait_for_all: 1 to prevent startup fencing.',
        'bug_id': 'MORPHL4-80',
        'affected_versions': 'VME 9.0.0_2, 2-node configurations',
        'prevention': 'Use 3+ node clusters for production. Configure proper fence delays. Add network redundancy for corosync.',
        'related_issues': 'Related to iptables persistence issue - if iptables lost on reboot, cluster communication fails causing fencing.',
        'category': 'cluster',
        'resolution_type': 'Config issue',
    },
    {
        'title': 'GFS2 volumes unusable without PR reservation keys on storage LUN',
        'products': ['GFS2', 'Alletra', 'Storage'],
        'symptoms': 'Unable to use GFS2 volumes on 9.x environment. System does not use PR (Persistent Reservation) keys but they exist on the storage LUN. GFS2 mount fails or goes read-only.',
        'root_cause': 'SCSI Persistent Reservations (PR) keys left on storage LUN from previous configuration. If the system is not configured to use PR keys but they exist on the LUN, GFS2 cannot properly manage locks.',
        'solution': '1. Check PR keys on LUN: sg_persist -i -k /dev/mapper/<device>\n2. Clear stale PR keys: sg_persist --out --clear --param-rk=<key> /dev/mapper/<device>\n3. Verify GFS2 mount options\n4. Restart GFS2/DLM services\n5. Verify with: dlm_tool status',
        'bug_id': 'MORPHL4-46',
        'affected_versions': 'Morpheus 9.x with GFS2 and Alletra storage',
        'prevention': 'Clean PR keys when decommissioning nodes. Document PR key management in runbook.',
        'related_issues': 'Related to MORPHL4-85 GFS2 datastore reclassification issue.',
        'category': 'storage',
        'resolution_type': 'Config issue',
    },
]
