"""Guided investigation runbooks for LogSherlock Pro.

Each runbook provides step-by-step investigation guidance for common issues.
Designed to help junior engineers systematically diagnose problems.
"""

RUNBOOKS = {
    'vm_not_booting': {
        'title': 'VM Not Booting Investigation',
        'category': 'virtualization',
        'steps': [
            {
                'description': 'Check VM state and recent events',
                'what_to_check': 'Current VM status and any error messages from the last start attempt',
                'log_file': '/var/log/libvirt/qemu/<vm-name>.log',
                'pattern_to_find': 'error|failed|permission denied|No such file',
                'normal_looks_like': 'VM transitions from "shut off" to "running" with no errors',
                'abnormal_means': 'Errors indicate why the VM cannot start - could be missing disk, permission issue, or resource problem',
                'suggested_commands': ['virsh list --all', 'virsh start <domain> --console', 'virsh dominfo <domain>'],
                'next_if_found': 'Check the specific error type and proceed to relevant step below',
                'explanation_for_juniors': 'First we check if the VM is actually failing to start or if it starts and crashes immediately. The QEMU log shows the exact error.',
            },
            {
                'description': 'Verify disk images are accessible',
                'what_to_check': 'All disk images referenced in VM XML exist and are readable',
                'log_file': '/var/log/libvirt/qemu/<vm-name>.log',
                'pattern_to_find': 'No such file|Permission denied|Could not open',
                'normal_looks_like': 'All disk paths exist with correct ownership (qemu:qemu or libvirt-qemu)',
                'abnormal_means': 'Missing or inaccessible disk images prevent VM boot',
                'suggested_commands': ['virsh dumpxml <domain> | grep "source file"', 'ls -la <disk-path>', 'qemu-img check <disk-path>'],
                'next_if_found': 'Restore missing disk or fix permissions with chown/chmod',
                'explanation_for_juniors': 'VMs need disk images to boot from. If the disk file was moved, deleted, or has wrong permissions, the VM cannot read it.',
            },
            {
                'description': 'Check host resource availability',
                'what_to_check': 'Sufficient RAM and CPU available on the host for this VM',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'Cannot allocate memory|not enough free memory|overcommit',
                'normal_looks_like': 'Free memory > VM configured memory; CPU count available',
                'abnormal_means': 'Host has insufficient resources - too many VMs or memory leak on host',
                'suggested_commands': ['free -h', 'virsh nodeinfo', 'virsh list --all | grep running | wc -l', 'cat /proc/meminfo | grep -i available'],
                'next_if_found': 'Shut down unused VMs or add resources to the host',
                'explanation_for_juniors': 'Each VM reserves memory from the host. If all host RAM is used by other VMs, new ones cannot start.',
            },
            {
                'description': 'Check for AppArmor/SELinux denials',
                'what_to_check': 'Security framework blocking libvirt/qemu access to resources',
                'log_file': '/var/log/audit/audit.log',
                'pattern_to_find': 'denied.*qemu|denied.*libvirt|avc:.*denied',
                'normal_looks_like': 'No denial messages related to qemu or libvirt',
                'abnormal_means': 'Security framework is blocking VM access to disks, network, or other resources',
                'suggested_commands': ['ausearch -m avc -ts recent', 'aa-status', 'getenforce', 'sealert -a /var/log/audit/audit.log'],
                'next_if_found': 'Add exception to AppArmor/SELinux or set to permissive for testing',
                'explanation_for_juniors': 'AppArmor and SELinux are security systems that control what programs can access. Sometimes they block legitimate VM operations.',
            },
            {
                'description': 'Check network bridge/interface availability',
                'what_to_check': 'Network bridges referenced in VM XML exist and are active',
                'log_file': '/var/log/libvirt/qemu/<vm-name>.log',
                'pattern_to_find': 'bridge.*not found|Cannot get interface|network.*not active',
                'normal_looks_like': 'Bridge interfaces UP and configured; virsh net-list shows networks active',
                'suggested_commands': ['virsh net-list --all', 'brctl show', 'ip link show type bridge', 'virsh dumpxml <domain> | grep "source network\\|source bridge"'],
                'next_if_found': 'Start the missing network or recreate the bridge',
                'abnormal_means': 'VM references a network bridge that does not exist or is down',
                'explanation_for_juniors': 'VMs connect to networks via bridges. If the bridge was deleted or the libvirt network is not started, the VM cannot get network access and may fail to start.',
            },
        ],
    },
    'storage_lun_issue': {
        'title': 'Storage LUN Issue Investigation',
        'category': 'storage',
        'steps': [
            {
                'description': 'Check multipath device status',
                'what_to_check': 'Current state of all paths to the affected LUN',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'mpath.*failed|path.*down|multipathd.*remove',
                'normal_looks_like': 'All paths show "active ready running" in multipath output',
                'abnormal_means': 'One or more paths are failed/faulty - indicates connectivity or array issue',
                'suggested_commands': ['multipath -ll', 'multipathd show paths', 'multipathd show maps', 'cat /etc/multipath.conf'],
                'next_if_found': 'Determine if single path or all paths are affected',
                'explanation_for_juniors': 'Multipath provides multiple routes to a storage LUN for redundancy. If paths fail, we need to determine if its a single path (partial) or total failure.',
            },
            {
                'description': 'Check SCSI/FC link status',
                'what_to_check': 'Physical connectivity to storage - HBA ports, FC links',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'link down|RSCN|port_state.*Linkdown|fc_remote_port.*delete',
                'normal_looks_like': 'All HBA ports show "Online" state',
                'abnormal_means': 'FC link is down - could be cable, switch port, or HBA failure',
                'suggested_commands': ['cat /sys/class/fc_host/host*/port_state', 'systool -c fc_host -v', 'cat /sys/class/fc_host/host*/statistics/link_failure_count'],
                'next_if_found': 'Check physical cables and switch ports; engage storage/network team',
                'explanation_for_juniors': 'Fibre Channel (FC) connects the server to the storage array via cables and switches. A link down means the physical or logical connection is broken.',
            },
            {
                'description': 'Check for I/O errors on the device',
                'what_to_check': 'Any I/O errors or timeouts reported by the kernel for this device',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'I/O error.*dev sd|Buffer I/O error|SCSI.*error|task.*blocked',
                'normal_looks_like': 'No I/O errors in recent logs',
                'abnormal_means': 'Active I/O errors mean the device cannot read/write - applications will fail',
                'suggested_commands': ['dmesg | grep -i "i/o error\\|scsi"', 'cat /sys/block/dm-*/stat', 'iostat -xz 1 5'],
                'next_if_found': 'Check storage array health and path status',
                'explanation_for_juniors': 'I/O errors mean the operating system tried to read or write to the disk but failed. This is serious - it means data operations are failing.',
            },
            {
                'description': 'Verify LUN visibility and SCSI scan',
                'what_to_check': 'Whether the LUN is still visible to the OS at the SCSI level',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'Attached scsi disk|scsi.*Direct-Access|sd.*logical blocks',
                'normal_looks_like': 'LUN appears in lsscsi output with correct size',
                'abnormal_means': 'LUN is not visible - may need SCSI rescan or storage-side check',
                'suggested_commands': ['lsscsi', 'sg_luns /dev/sg*', 'echo "- - -" > /sys/class/scsi_host/host0/scan', 'multipath -r'],
                'next_if_found': 'If LUN missing, check storage array zoning and LUN masking',
                'explanation_for_juniors': 'The server discovers storage LUNs via SCSI scanning. If a LUN disappears, it might be a zoning issue on the FC switch or masking on the storage array.',
            },
        ],
    },
    'gfs2_problems': {
        'title': 'GFS2 Filesystem Problems Investigation',
        'category': 'filesystem',
        'steps': [
            {
                'description': 'Check GFS2 mount status and recent errors',
                'what_to_check': 'Whether GFS2 is mounted, read-only, or withdrawn',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'GFS2.*withdraw|GFS2.*read-only|gfs2.*error|dlm.*error',
                'normal_looks_like': 'GFS2 mounted read-write with no errors; mount shows rw',
                'abnormal_means': 'GFS2 has encountered an error - may be withdrawn or read-only',
                'suggested_commands': ['mount | grep gfs2', 'cat /proc/mounts | grep gfs2', 'dmesg | grep -i gfs2', 'gfs2_tool df /mount/point'],
                'next_if_found': 'Determine if its a withdraw (critical) or read-only remount',
                'explanation_for_juniors': 'GFS2 is a cluster filesystem shared between nodes. When it detects problems, it withdraws (disconnects) to prevent data corruption. This is protective but means the filesystem is unusable.',
            },
            {
                'description': 'Check DLM lock status',
                'what_to_check': 'Distributed Lock Manager health - required for GFS2 operation',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'dlm.*error|dlm.*timeout|dlm_controld.*fail',
                'normal_looks_like': 'dlm_tool ls shows all lockspaces with all nodes joined',
                'abnormal_means': 'DLM errors mean lock coordination is failing - often due to cluster communication issues',
                'suggested_commands': ['dlm_tool ls', 'dlm_tool lockdebug <ls_name>', 'dlm_tool status', 'cat /sys/kernel/dlm/*/recover_status'],
                'next_if_found': 'Check cluster communication (corosync) next',
                'explanation_for_juniors': 'DLM is the lock manager that prevents multiple nodes from writing to the same file simultaneously. If DLM breaks, GFS2 cannot safely operate.',
            },
            {
                'description': 'Check underlying storage health',
                'what_to_check': 'Whether the block device under GFS2 is healthy and accessible',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'I/O error|Buffer I/O|scsi.*error|mpath.*failed',
                'normal_looks_like': 'No I/O errors; multipath shows all paths active',
                'abnormal_means': 'Storage errors are causing GFS2 failures - fix storage first',
                'suggested_commands': ['multipath -ll', 'dmesg | grep -i "i/o error"', 'iostat -xz 1 3', 'pvs; vgs; lvs'],
                'next_if_found': 'Storage is the root cause - follow storage_lun_issue runbook',
                'explanation_for_juniors': 'GFS2 sits on top of block storage. If the storage has problems, GFS2 will also have problems. Always check storage first.',
            },
            {
                'description': 'Check cluster membership',
                'what_to_check': 'All nodes that should be in the cluster are present and communicating',
                'log_file': '/var/log/cluster/corosync.log',
                'pattern_to_find': 'membership.*changed|node.*left|quorum.*lost',
                'normal_looks_like': 'All expected nodes in membership; quorum maintained',
                'abnormal_means': 'Node loss can cause DLM recovery which can trigger GFS2 issues',
                'suggested_commands': ['pcs status', 'corosync-cmapctl | grep members', 'corosync-quorumtool', 'crm_mon -1'],
                'next_if_found': 'Check why node left - network, crash, or fencing',
                'explanation_for_juniors': 'GFS2 requires all nodes to be in communication. When a node leaves unexpectedly, the remaining nodes must recover its locks, which can cause brief hangs.',
            },
            {
                'description': 'Attempt recovery',
                'what_to_check': 'Whether the filesystem can be recovered without data loss',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'gfs2.*mounted|gfs2.*recovery|journal.*replayed',
                'normal_looks_like': 'Successful mount with journal replay completed',
                'abnormal_means': 'Mount fails even after fixing underlying issues - may need fsck',
                'suggested_commands': ['umount /mount/point', 'mount -t gfs2 /dev/mapper/vg-lv /mount/point', 'fsck.gfs2 -n /dev/mapper/vg-lv', 'gfs2_edit -p journal0 /dev/mapper/vg-lv'],
                'next_if_found': 'If mount succeeds, verify data integrity; if not, run fsck.gfs2',
                'explanation_for_juniors': 'Recovery involves unmounting the broken filesystem, fixing the underlying issue, and remounting. fsck checks and repairs filesystem structure but should be last resort.',
            },
        ],
    },

    'cluster_ha_issue': {
        'title': 'Cluster HA Issue Investigation',
        'category': 'cluster',
        'steps': [
            {
                'description': 'Check overall cluster status',
                'what_to_check': 'Current state of all nodes and resources in the cluster',
                'log_file': '/var/log/pacemaker/pacemaker.log',
                'pattern_to_find': 'error|fence|fail|offline|unclean',
                'normal_looks_like': 'All nodes Online; all resources Started; no failed actions',
                'abnormal_means': 'Nodes offline, resources stopped/failed, or fencing events indicate cluster problems',
                'suggested_commands': ['pcs status', 'pcs status --full', 'crm_mon -1Arf', 'pcs cluster status'],
                'next_if_found': 'Identify which component is failing - node, resource, or fencing',
                'explanation_for_juniors': 'The cluster status gives you the big picture. Look for anything marked as OFFLINE, FAILED, or Stopped that should be running.',
            },
            {
                'description': 'Check corosync communication',
                'what_to_check': 'Cluster heartbeat communication between nodes',
                'log_file': '/var/log/cluster/corosync.log',
                'pattern_to_find': 'ring.*error|token.*timeout|membership.*changed|retransmit',
                'normal_looks_like': 'No ring errors; token passing normal; stable membership',
                'abnormal_means': 'Communication issues cause nodes to be falsely marked as dead, triggering unnecessary fencing',
                'suggested_commands': ['corosync-cfgtool -s', 'corosync-cmapctl | grep runtime.totem', 'corosync-quorumtool -s', 'ip addr show'],
                'next_if_found': 'Check network between nodes - switches, cables, interface status',
                'explanation_for_juniors': 'Corosync sends heartbeats between cluster nodes. If heartbeats stop arriving, the cluster thinks a node is dead. This is often a network problem, not a real node failure.',
            },
            {
                'description': 'Check quorum status',
                'what_to_check': 'Whether the cluster has quorum (majority of nodes)',
                'log_file': '/var/log/cluster/corosync.log',
                'pattern_to_find': 'quorum lost|not quorate|partition',
                'normal_looks_like': 'Cluster is quorate; expected votes match',
                'abnormal_means': 'Lost quorum means the cluster will stop resources to prevent split-brain. This is by design.',
                'suggested_commands': ['corosync-quorumtool', 'pcs quorum status', 'pcs quorum device status'],
                'next_if_found': 'Determine which nodes are missing and why',
                'explanation_for_juniors': 'Quorum means majority. In a 3-node cluster, you need 2 nodes. Without quorum, the cluster stops everything to prevent two halves from running independently (split-brain).',
            },
            {
                'description': 'Check fencing (STONITH) status and history',
                'what_to_check': 'Whether fencing is configured and working correctly',
                'log_file': '/var/log/pacemaker/pacemaker.log',
                'pattern_to_find': 'fence|stonith|reboot|power.*off',
                'normal_looks_like': 'Fence devices configured and last-test shows success',
                'abnormal_means': 'Fencing failures can leave nodes in "unclean" state and block resource recovery',
                'suggested_commands': ['pcs stonith show', 'pcs stonith history', 'stonith_admin -L', 'pcs stonith fence <node> --dry-run'],
                'next_if_found': 'Verify fence device credentials and network access to IPMI/iLO',
                'explanation_for_juniors': 'Fencing (STONITH) is the mechanism to forcibly reboot a dead node. If fencing cannot work (wrong password, network issue), the cluster gets stuck because it cannot safely reassign resources.',
            },
            {
                'description': 'Check resource failures and cleanup',
                'what_to_check': 'Which resources have failed and why',
                'log_file': '/var/log/pacemaker/pacemaker.log',
                'pattern_to_find': 'operation.*failed|monitor.*error|start.*error|stop.*error',
                'normal_looks_like': 'No failed resource actions; all monitors return 0',
                'abnormal_means': 'Resource failures trigger migration or stop. Check why the resource agent failed.',
                'suggested_commands': ['pcs resource failcount show', 'pcs resource cleanup <resource>', 'pcs resource restart <resource>', 'crm_resource -W -r <resource>'],
                'next_if_found': 'Check the specific resource agent logs and underlying service',
                'explanation_for_juniors': 'Resources are services managed by the cluster. When a resource fails, the cluster tracks the failure. Too many failures and it gives up. Cleanup resets the counter.',
            },
        ],
    },

    'network_connectivity': {
        'title': 'Network Connectivity Investigation',
        'category': 'network',
        'steps': [
            {
                'description': 'Check interface status and IP configuration',
                'what_to_check': 'All network interfaces are UP with correct IPs assigned',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'link down|carrier lost|NIC Link is Down|interface.*down',
                'normal_looks_like': 'All interfaces UP with correct IPs; link detected',
                'abnormal_means': 'Interface down or no IP means the network path is broken at layer 1/2',
                'suggested_commands': ['ip addr show', 'ip link show', 'ethtool <interface>', 'cat /proc/net/bonding/bond0'],
                'next_if_found': 'Check physical cable and switch port; try ifup/ip link set up',
                'explanation_for_juniors': 'Start from the bottom up. If the interface itself is down, nothing above it (routing, DNS, applications) will work.',
            },
            {
                'description': 'Check routing table and default gateway',
                'what_to_check': 'Correct routes exist to reach the destination',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'unreachable|no route|RTNETLINK|route.*deleted',
                'normal_looks_like': 'Default gateway present and reachable; specific routes for subnets exist',
                'abnormal_means': 'Missing routes mean traffic cannot reach its destination even if the interface is up',
                'suggested_commands': ['ip route show', 'ip route get <destination>', 'ping -c 3 <gateway>', 'traceroute <destination>'],
                'next_if_found': 'Add missing route or fix default gateway configuration',
                'explanation_for_juniors': 'Routes tell the OS where to send traffic. Without a default route, the system cannot reach anything outside its local subnet.',
            },
            {
                'description': 'Check DNS resolution',
                'what_to_check': 'DNS is working and can resolve hostnames',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'resolve.*fail|NXDOMAIN|SERVFAIL|name.*not.*known',
                'normal_looks_like': 'nslookup/dig returns correct IP addresses for hostnames',
                'abnormal_means': 'DNS failure means services using hostnames will fail even if network is actually working',
                'suggested_commands': ['cat /etc/resolv.conf', 'nslookup google.com', 'dig <hostname>', 'systemd-resolve --status'],
                'next_if_found': 'Verify DNS server is reachable; check /etc/resolv.conf',
                'explanation_for_juniors': 'DNS translates names (like server1.example.com) to IP addresses. If DNS is broken, you can still ping by IP but not by name.',
            },
            {
                'description': 'Check firewall rules',
                'what_to_check': 'Firewall is not blocking required traffic',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'REJECT|DROP|blocked|iptables.*denied',
                'normal_looks_like': 'Required ports are allowed in firewall rules',
                'abnormal_means': 'Firewall is dropping traffic that should be allowed',
                'suggested_commands': ['iptables -L -n -v', 'firewall-cmd --list-all', 'nft list ruleset', 'ss -tlnp | grep <port>'],
                'next_if_found': 'Add firewall rule to allow required traffic',
                'explanation_for_juniors': 'Firewalls filter network traffic. A misconfigured firewall can silently drop packets, making it look like the remote service is down when its actually the local firewall blocking.',
            },
            {
                'description': 'Check for network bond/team issues',
                'what_to_check': 'If using bonded interfaces, verify bond health',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'bond.*link.*down|slave.*link.*down|bond.*interface.*removed',
                'normal_looks_like': 'All bond members active; MII status UP for all slaves',
                'abnormal_means': 'Bond degraded with fewer active members reduces redundancy; all members down = outage',
                'suggested_commands': ['cat /proc/net/bonding/bond*', 'teamdctl team0 state', 'ip link show master bond0', 'ethtool bond0'],
                'next_if_found': 'Check individual NIC status and switch ports for each bond member',
                'explanation_for_juniors': 'Network bonding combines multiple NICs for redundancy. If bond members fail, the bond may still work with reduced bandwidth until all members are down.',
            },
        ],
    },

    'disk_space_full': {
        'title': 'Disk Space Full Investigation',
        'category': 'filesystem',
        'steps': [
            {
                'description': 'Identify which filesystem is full',
                'what_to_check': 'Which mount point has reached 100% or near-full capacity',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'No space left on device|ENOSPC|disk.*full|quota.*exceeded',
                'normal_looks_like': 'All filesystems below 80% usage',
                'abnormal_means': 'Filesystem at 100% blocks all writes - can crash applications and prevent logging',
                'suggested_commands': ['df -h', 'df -i', 'du -sh /* | sort -rh | head -20', 'lsblk'],
                'next_if_found': 'Identify the full mount point and proceed to find large files',
                'explanation_for_juniors': 'df -h shows disk usage. df -i shows inode usage (you can run out of inodes even with free space if you have millions of tiny files).',
            },
            {
                'description': 'Find large files consuming space',
                'what_to_check': 'What is using the most space on the full filesystem',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'No space left',
                'normal_looks_like': 'No unexpectedly large files; log rotation working properly',
                'abnormal_means': 'Giant log files, core dumps, or temp files consuming all space',
                'suggested_commands': ['find /var -xdev -size +100M -exec ls -lh {} \\;', 'du -sh /var/log/*  | sort -rh | head', 'find / -xdev -type f -size +1G', 'ls -lhS /var/log/'],
                'next_if_found': 'Determine if large files can be safely deleted or truncated',
                'explanation_for_juniors': 'Large files are usually logs that were not rotated, core dumps from crashes, or temp files from failed operations. Finding them tells you what to clean up.',
            },
            {
                'description': 'Check for deleted but open files',
                'what_to_check': 'Files deleted but still held open by processes (still consuming space)',
                'log_file': '/proc filesystem',
                'pattern_to_find': 'deleted',
                'normal_looks_like': 'No large deleted files held open',
                'abnormal_means': 'Deleted files still consume space until the process holding them closes - may need service restart',
                'suggested_commands': ['lsof +L1', 'lsof | grep deleted | sort -k7 -rn | head', 'find /proc/*/fd -ls 2>/dev/null | grep deleted'],
                'next_if_found': 'Restart the process holding the deleted file to free space immediately',
                'explanation_for_juniors': 'In Linux, deleting a file only removes the name. If a process still has the file open, the space is not freed until the process closes it. This is why disk space does not free up after deleting files sometimes.',
            },
            {
                'description': 'Check log rotation configuration',
                'what_to_check': 'Whether logrotate is configured and running properly',
                'log_file': '/var/lib/logrotate/logrotate.status',
                'pattern_to_find': 'error|fail',
                'normal_looks_like': 'All logs rotated recently; no errors in logrotate status',
                'abnormal_means': 'Logrotate not running means logs grow forever until disk is full',
                'suggested_commands': ['cat /etc/logrotate.conf', 'ls /etc/logrotate.d/', 'logrotate -d /etc/logrotate.conf', 'systemctl status logrotate.timer'],
                'next_if_found': 'Fix logrotate config and run manually: logrotate -f /etc/logrotate.conf',
                'explanation_for_juniors': 'Logrotate automatically compresses and removes old log files. If it stops working, logs grow indefinitely.',
            },
            {
                'description': 'Extend filesystem if cleanup insufficient',
                'what_to_check': 'Whether the filesystem can be grown (LVM) or if physical disk needs adding',
                'log_file': 'N/A',
                'pattern_to_find': 'N/A',
                'normal_looks_like': 'VG has free space; filesystem supports online resize',
                'abnormal_means': 'No free space in volume group - need physical disk or migration',
                'suggested_commands': ['vgs', 'lvs', 'pvs', 'lvextend -l +100%FREE /dev/vg/lv && resize2fs /dev/vg/lv'],
                'next_if_found': 'If VG has space, extend LV and resize filesystem. If not, add physical disk.',
                'explanation_for_juniors': 'LVM lets you grow filesystems without downtime. If the volume group has free space, you can extend the logical volume and then grow the filesystem on top of it.',
            },
        ],
    },

    'deployment_failure': {
        'title': 'Deployment Failure Investigation',
        'category': 'application',
        'steps': [
            {
                'description': 'Check deployment/provisioning logs',
                'what_to_check': 'The specific error message from the deployment tool',
                'log_file': '/var/log/morpheus/morpheus-ui/current',
                'pattern_to_find': 'provision.*fail|deploy.*fail|error.*instance|timeout.*provision',
                'normal_looks_like': 'Deployment progresses through stages and completes successfully',
                'abnormal_means': 'Deployment stopped at a specific stage - the error identifies what went wrong',
                'suggested_commands': ['tail -100 /var/log/morpheus/morpheus-ui/current', 'grep -i "error\\|fail" /var/log/morpheus/morpheus-ui/current | tail -20', 'morpheus instances get <id>'],
                'next_if_found': 'Identify which stage failed and proceed to the relevant check below',
                'explanation_for_juniors': 'Deployments have multiple stages: resource allocation, network setup, disk creation, OS install, configuration. Finding which stage failed narrows the troubleshooting.',
            },
            {
                'description': 'Check resource availability on target',
                'what_to_check': 'Sufficient CPU, memory, storage on the target hypervisor/cloud',
                'log_file': '/var/log/morpheus/morpheus-ui/current',
                'pattern_to_find': 'insufficient.*resource|not enough|capacity|quota.*exceeded',
                'normal_looks_like': 'Target has free resources exceeding deployment requirements',
                'abnormal_means': 'Target is at capacity - cannot allocate required CPU/RAM/disk',
                'suggested_commands': ['virsh nodeinfo', 'free -h', 'df -h', 'virsh pool-info <pool>'],
                'next_if_found': 'Free resources or select a different target host/cloud',
                'explanation_for_juniors': 'Every VM deployment needs resources. If the host is full, the deployment will fail. Check what is available versus what is requested.',
            },
            {
                'description': 'Check network/DHCP during provisioning',
                'what_to_check': 'VM got an IP address and can reach required services',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'DHCP.*NACK|no.*lease|network.*unreachable|cloud-init.*fail',
                'normal_looks_like': 'VM receives IP via DHCP or static config applied correctly',
                'abnormal_means': 'No IP means the VM cannot download packages, reach config management, or report back to orchestrator',
                'suggested_commands': ['virsh domifaddr <domain>', 'journalctl -u NetworkManager', 'cat /var/log/cloud-init.log', 'dhclient -v <interface>'],
                'next_if_found': 'Check DHCP server, network bridge configuration, VLAN tagging',
                'explanation_for_juniors': 'During provisioning, the new VM needs network access to download software and report completion. DHCP issues are a common cause of deployment timeouts.',
            },
            {
                'description': 'Check cloud-init / user-data execution',
                'what_to_check': 'Whether the post-boot configuration script ran successfully',
                'log_file': '/var/log/cloud-init-output.log',
                'pattern_to_find': 'error|traceback|fail|command.*returned.*non-zero',
                'normal_looks_like': 'cloud-init reports all modules ran successfully',
                'abnormal_means': 'Configuration script failed - could be package install failure, script error, or timeout',
                'suggested_commands': ['cat /var/log/cloud-init-output.log', 'cloud-init status --long', 'cat /var/log/cloud-init.log | grep -i error', 'cloud-init analyze show'],
                'next_if_found': 'Fix the failing script/command in the instance configuration template',
                'explanation_for_juniors': 'Cloud-init runs scripts after first boot to configure the VM (install packages, set up users, configure services). If these scripts fail, the VM is not properly configured.',
            },
            {
                'description': 'Check agent installation and callback',
                'what_to_check': 'Whether the management agent installed and connected back to orchestrator',
                'log_file': '/var/log/morpheus/morpheus-node-agent/current',
                'pattern_to_find': 'connection.*refused|timeout|ssl.*error|agent.*fail',
                'normal_looks_like': 'Agent connects to appliance and reports healthy status',
                'abnormal_means': 'Agent cannot reach the management server - firewall, DNS, or SSL issue',
                'suggested_commands': ['systemctl status morpheus-node-agent', 'curl -k https://<appliance>/api/whoami', 'cat /etc/morpheus/morpheus-node-agent/agent.conf', 'openssl s_client -connect <appliance>:443'],
                'next_if_found': 'Check firewall rules, DNS resolution to appliance, SSL certificate validity',
                'explanation_for_juniors': 'The agent is software installed in the VM that talks back to the management platform. If it cannot connect (firewall, wrong address, bad certificate), the deployment appears stuck.',
            },
        ],
    },
    'gfs2_heartbeat_deadlock': {
        'title': 'GFS2 Heartbeat Deadlock Investigation (Mass VM Shutdown)',
        'category': 'cluster',
        'steps': [
            {
                'description': 'Confirm heartbeat write failures in agent logs',
                'what_to_check': 'VME agent logs for MvmHeartbeatFailover errors showing heartbeat write failures',
                'log_file': '/var/log/morpheus-agent/morphd.log (or agent stdout log)',
                'pattern_to_find': 'Unable to Write Heartbeat|Failed to write heartbeat file|All heartbeat datastore paths have been unhealthy|File exists check timed out',
                'normal_looks_like': 'Wrote heartbeat file for host <hostname> at <timestamp> (every 20 seconds)',
                'abnormal_means': 'Agent cannot write to GFS2 heartbeat datastore. After 6 failures (~2 min), all VMs will be shut down.',
                'suggested_commands': ['grep -i "heartbeat" /var/log/morpheus-agent/*.log | tail -50', 'grep -i "isolation\\|shutdown" /var/log/morpheus-agent/*.log'],
                'next_if_found': 'Proceed to check GFS2 filesystem health (step 2)',
                'explanation_for_juniors': 'The VME agent writes a heartbeat file to shared GFS2 storage every 20 seconds. If it fails 6 times in a row, it assumes the host is isolated from the cluster and shuts down all VMs to prevent split-brain (two hosts running the same VM = data corruption).',
            },
            {
                'description': 'Check for GFS2 glock deadlock in kernel logs',
                'what_to_check': 'Kernel/dmesg for processes blocked in D-state with GFS2 glock functions in call trace',
                'log_file': '/var/log/syslog or dmesg',
                'pattern_to_find': 'blocked for more than.*seconds|task:.*state:D|gfs2_glock_wait|gfs2_create_inode|gfs2_glock_nq',
                'normal_looks_like': 'No hung task warnings. Processes complete normally.',
                'abnormal_means': 'GFS2 filesystem is deadlocked. All I/O to GFS2 is frozen. This is the root cause of heartbeat failures.',
                'suggested_commands': ['dmesg | grep -i "blocked for more than"', 'dmesg | grep -i "gfs2_glock"', 'ps aux | awk "$8~/D/"', 'cat /proc/*/wchan | sort | uniq -c | sort -rn | head'],
                'next_if_found': 'Identify what triggered the deadlock (step 3)',
                'explanation_for_juniors': 'D-state means a process is stuck waiting for I/O that never completes. When you see gfs2_glock_wait in the call trace, it means the process is waiting for a GFS2 filesystem lock that will never be granted - a deadlock.',
            },
            {
                'description': 'Identify the trigger event (what caused the deadlock)',
                'what_to_check': 'What operations were running just before the deadlock - typically SCSI rescan + pool refresh + pcs resource update',
                'log_file': '/var/log/auth.log or /var/log/syslog',
                'pattern_to_find': 'echo.*scsi_host.*scan|virsh pool-refresh|pcs resource meta.*gfs2|scsi.*rescan',
                'normal_looks_like': 'These operations complete quickly without overlap',
                'abnormal_means': 'Concurrent execution of SCSI rescan + GFS2 pool refresh + pacemaker resource update creates glock contention leading to deadlock',
                'suggested_commands': ['grep -E "scsi_host|pool-refresh|pcs resource" /var/log/auth.log', 'grep -E "scsi_host|pool-refresh|pcs resource" /var/log/syslog', 'journalctl --since "<incident_time - 5min>" --until "<incident_time>"'],
                'next_if_found': 'This confirms the VME 8.1.0 GFS2 deadlock bug (MORPH-11774). Proceed to check VM status.',
                'explanation_for_juniors': 'When a VM starts, the system rescans SCSI buses to find storage, refreshes GFS2 pools, and updates cluster resources. In VME 8.1.0, doing all these at once on GFS2 creates a lock conflict where each operation waits for the other - a deadlock.',
            },
            {
                'description': 'Check which VMs were affected and their shutdown behavior',
                'what_to_check': 'Agent logs for VM power-off entries to determine which VMs shut down vs survived',
                'log_file': '/var/log/morpheus-agent/morphd.log',
                'pattern_to_find': 'Successfully powered off VM|powered off VM.*retry|VM.*never acknowledged',
                'normal_looks_like': 'No unexpected VM shutdowns',
                'abnormal_means': 'Mass VM shutdown triggered. VMs that shut down immediately had responsive QEMU processes. VMs that survived had QEMU processes also stuck in D-state (could not receive shutdown command).',
                'suggested_commands': ['grep -i "powered off VM" /var/log/morpheus-agent/*.log', 'virsh list --all', 'grep -c "powered off" /var/log/morpheus-agent/*.log'],
                'next_if_found': 'Note surviving VMs - they survived because their QEMU processes were hung in D-state too.',
                'explanation_for_juniors': 'The agent tries to shut down VMs via libvirt/QEMU guest agent. If a VM QEMU process is also stuck in D-state (waiting for GFS2), it cannot process the shutdown command. Ironically, being stuck saved those VMs from being shut down.',
            },
            {
                'description': 'Check if failover was attempted by other nodes',
                'what_to_check': 'Agent logs on OTHER cluster nodes to see if they detected the affected host as offline',
                'log_file': '/var/log/morpheus-agent/morphd.log (on other nodes)',
                'pattern_to_find': 'host.*offline|recover.*VM|failover.*initiated|reading.*hb.properties',
                'normal_looks_like': 'Other nodes detect host offline within 2-3 heartbeat cycles and initiate VM recovery',
                'abnormal_means': 'Other nodes did NOT detect the failure. This means GFS2 deadlock also affected their ability to read the affected host hb.properties file on the shared GFS2 mount.',
                'suggested_commands': ['grep -i "offline\\|recover\\|failover" /var/log/morpheus-agent/*.log', 'grep -i "hb.properties" /var/log/morpheus-agent/*.log'],
                'next_if_found': 'Confirms cluster-wide GFS2 impact. VME Manager loss also prevents orchestrated failover.',
                'explanation_for_juniors': 'For failover to work, other nodes must: 1) Read the dead host heartbeat file and see it is stale, 2) Have VME Manager running to orchestrate recovery. If GFS2 is deadlocked cluster-wide or VME Manager is down, neither condition is met.',
            },
            {
                'description': 'Determine resolution path',
                'what_to_check': 'Current host state and recommended actions',
                'log_file': 'N/A - action step',
                'pattern_to_find': 'N/A',
                'normal_looks_like': 'N/A',
                'abnormal_means': 'N/A',
                'suggested_commands': ['mount | grep gfs2', 'pcs status', 'virsh list --all', 'systemctl status corosync pacemaker'],
                'next_if_found': 'Apply resolution steps below',
                'explanation_for_juniors': 'Resolution steps:\n1. Reboot affected host (clears stale GFS2 locks)\n2. Verify GFS2 mounts healthy after reboot\n3. Manually start VMs (virsh start <domain>)\n4. Upgrade to VME 8.1.2+ (fixes MORPH-11774)\n5. Long-term: HPE replacing GFS2 coordination in VME 9.0+',
            },
        ],
    },
    'cluster_storage_fencing_cascade': {
        'title': 'Cluster-Wide Storage Fencing Cascade Investigation (Datastore Decommission)',
        'category': 'cluster',
        'steps': [
            {
                'description': 'Identify the triggering event (what change was made)',
                'what_to_check': 'Recent change activities — specifically datastore decommissions, storage removals, or Pacemaker resource changes',
                'log_file': '/var/log/morpheus/morpheus-ui/current or Morpheus audit log',
                'pattern_to_find': 'datastore.*stop|datastore.*remov|decommission|pcs resource delete|resource.*cleanup',
                'normal_looks_like': 'Datastore removed cleanly: unmount completes → resource removed → no errors',
                'abnormal_means': 'Datastore marked Stopped but unmount did not complete. Pacemaker resource removed while GFS2 still mounted = orphaned resource.',
                'suggested_commands': ['pcs status --full', 'pcs resource show --full', 'grep -i "datastore\\|decommission" /var/log/morpheus/morpheus-ui/current | tail -50'],
                'next_if_found': 'Confirm the decommission triggered the cascade (step 2)',
                'explanation_for_juniors': 'A datastore decommission means removing a storage volume that is no longer needed. If the system removes the cluster configuration before the filesystem is properly unmounted, the cluster loses control of that resource and panics.',
            },
            {
                'description': 'Check for STONITH fencing events',
                'what_to_check': 'Pacemaker STONITH (fencing) history to see which nodes were fenced and in what order',
                'log_file': '/var/log/pacemaker/pacemaker.log or /var/log/cluster/corosync.log',
                'pattern_to_find': 'STONITH.*action|fencing.*node|stonith-ng|fence_action|Initiating.*fenc',
                'normal_looks_like': 'No STONITH events during normal operation',
                'abnormal_means': 'Multiple nodes fenced in sequence = fencing cascade. This is the cluster trying to protect data integrity by isolating nodes it cannot manage.',
                'suggested_commands': ['pcs stonith history', 'grep -i "stonith\\|fence" /var/log/pacemaker/pacemaker.log | tail -50', 'corosync-cfgtool -s'],
                'next_if_found': 'Check the cascade impact on GFS2 volumes (step 3)',
                'explanation_for_juniors': 'STONITH is the cluster safety mechanism. When it cannot manage a resource properly, it reboots the offending node. A cascade means multiple nodes got fenced one after another — usually because the root cause (orphaned resource) was not resolved by fencing the first node.',
            },
            {
                'description': 'Assess GFS2 volume read-only transitions',
                'what_to_check': 'Which GFS2 datastores transitioned to read-only and when',
                'log_file': '/var/log/messages or dmesg',
                'pattern_to_find': 'read-only|remounting.*ro|GFS2.*withdraw|DLM.*error|dlm.*fail',
                'normal_looks_like': 'GFS2 volumes mounted read-write with no errors',
                'abnormal_means': 'Multiple volumes going read-only simultaneously = cluster-wide storage fencing. ALL VMs on affected datastores lose write access.',
                'suggested_commands': ['mount | grep gfs2', 'dmesg | grep -i "read-only\\|gfs2\\|dlm"', 'cat /proc/mounts | grep gfs2', 'dlm_tool status'],
                'next_if_found': 'Determine scope: list all affected datastores and VMs (step 4)',
                'explanation_for_juniors': 'When the cluster fences nodes, it protects shared filesystems by making them read-only. This prevents data corruption but means all VMs using those filesystems cannot write data — effectively a full outage.',
            },
            {
                'description': 'Check DLM and multipath service status',
                'what_to_check': 'DLM (Distributed Lock Manager) and multipath health — both are required for GFS2',
                'log_file': '/var/log/messages',
                'pattern_to_find': 'dlm.*error|multipathd.*fail|multipath.*path.*down|DLM.*connection',
                'normal_looks_like': 'DLM lockspaces active, multipath showing all paths active',
                'abnormal_means': 'DLM failure means GFS2 cannot coordinate locks between nodes. Multipath failure means storage paths are unreachable.',
                'suggested_commands': ['dlm_tool status', 'dlm_tool lockdebug', 'multipath -ll', 'systemctl status dlm multipathd', 'pcs resource show dlm-clone'],
                'next_if_found': 'Services need restart after root cause is fixed (step 5)',
                'explanation_for_juniors': 'DLM is like a traffic controller for shared storage — it ensures two nodes do not write to the same spot simultaneously. If DLM fails, the filesystem goes read-only to prevent corruption. Multipath manages the physical paths to the storage array.',
            },
            {
                'description': 'Check STONITH device configuration validity',
                'what_to_check': 'Whether the STONITH/fencing device still references valid paths (deleted datastores can break unfencing)',
                'log_file': '/var/log/pacemaker/pacemaker.log',
                'pattern_to_find': 'unfence.*fail|fence.*device.*not found|stonith.*invalid.*path|fence.*unable',
                'normal_looks_like': 'STONITH device paths valid and responsive',
                'abnormal_means': 'STONITH still references a deleted device path. This prevents the unfencing process from completing — the cluster cannot automatically recover.',
                'suggested_commands': ['pcs stonith show', 'pcs stonith config', 'pcs property show', 'grep -i "stonith" /etc/pacemaker/*.conf'],
                'next_if_found': 'Update STONITH config to remove references to deleted devices before attempting recovery',
                'explanation_for_juniors': 'After fencing a node, the cluster must unfence it to bring it back. If the fencing device references a deleted storage path, unfencing fails and the node stays locked out. You must fix the STONITH config before the cluster can heal.',
            },
            {
                'description': 'Execute recovery plan (FSCK → Mount → Restore VMs)',
                'what_to_check': 'Systematic recovery: filesystem integrity check on EVERY affected volume before remounting',
                'log_file': 'N/A - action step',
                'pattern_to_find': 'N/A',
                'normal_looks_like': 'N/A',
                'abnormal_means': 'N/A',
                'suggested_commands': ['fsck.gfs2 -y /dev/mapper/<datastore_device>', 'mount -t gfs2 /dev/mapper/<device> /mnt/<mountpoint>', 'pcs resource cleanup', 'virsh list --all', 'virsh start <domain>'],
                'next_if_found': 'N/A',
                'explanation_for_juniors': 'Recovery steps (CRITICAL — follow this order):\\n1. Reboot all affected cluster nodes to clear stale state\\n2. Fix STONITH device config (remove deleted device references)\\n3. Run fsck.gfs2 on EVERY affected datastore — do NOT skip this, data may be inconsistent\\n4. Mount datastores only AFTER fsck passes clean\\n5. Process multiple volumes in parallel for speed\\n6. Start VMs in priority order (critical services first)\\n7. Validate each VM after start\\n8. Prevention: NEVER decommission datastores via Morpheus UI. Use manual unmount → pcs resource delete → Morpheus remove.',
            },
        ],
    },
}
