"""HPE VM Essentials Manager - Complete Operations Knowledge Base.

Covers: HPE VM Essentials v8.x & v9.x, KVM/libvirt/Morpheus
Contains 41+ entries covering: Installation, Networking, Storage, Monitoring,
Troubleshooting, Production Issues, Security, Performance, Daily Operations,
Health Monitoring, Storage Validation, Log Analysis.

Author: Krishna Chaithanya Yada
"""

VME_GUIDE_ENTRIES = [
    # === INSTALLATION & DEPLOYMENT ===
    {
        'title': 'HPE VM Essentials Manager Appliance Installation (v9.x Wizard)',
        'category': 'Installation',
        'products': ['VME', 'KVM'],
        'description': 'Automated deployment via graphical wizard from admin machine.',
        'steps': [
            '1. Download Manager ISO from HPE portal',
            '2. Mount on administrative machine',
            '3. Launch installer wizard',
            '4. Enter target HVM host IP + SSH credentials',
            '5. Define VM params: Static IP, subnet, gateway, admin username, password',
            '6. Set Appliance URL (FQDN - must be pre-registered in corporate DNS)',
            '7. Select VM size → Click Install → Wizard handles everything',
        ],
        'prerequisites': 'Network bonding must be configured BEFORE installation. Host must have Intel VT-x/AMD-V enabled.',
        'notes': 'DB schema generation on first boot takes up to 60 minutes. Monitor with: tail -f /var/log/morpheus/morpheus-ui/current',
    },
    {
        'title': 'HPE VM Essentials Manager Installation (v8.x Host Console)',
        'category': 'Installation',
        'products': ['VME', 'KVM'],
        'description': 'Deploy directly from HVM host terminal via text-based menus.',
        'steps': [
            '1. SCP ISO to host: scp HPE_VM_Essentials_SW_image_v8.x.iso root@<host-ip>:/var/lib/libvirt/images/',
            '2. Mount ISO: sudo mount -o loop /var/lib/libvirt/images/HPE_VM_Essentials_SW_image_v8.x.iso /media',
            '3. Launch menu: sudo hpe-vm',
            '4. Select deployment option from menu',
            '5. Configure: IP, DNS, Appliance URL, image path, interface (bond0.100)',
            '6. Authorize execution (DB generation takes up to 60 min)',
        ],
        'prerequisites': 'Network bonding configured, SSH access to host, sufficient disk space.',
        'notes': 'Deployment may hang at 93% — this is normal during DB schema generation. Wait up to 60 minutes.',
    },
    {
        'title': 'Network Bonding Setup (CRITICAL Pre-Installation Requirement)',
        'category': 'Installation',
        'products': ['VME', 'KVM'],
        'description': 'Network bonding must be configured before HPE VM Essentials deployment. Combines two NICs for redundancy and bandwidth.',
        'steps': [
            '1. Identify NICs: ip link show',
            '2. Create bond: sudo nmcli connection add type bond con-name bond0 ifname bond0 bond.options "mode=802.3ad,miimon=100,lacp_rate=fast"',
            '3. Add slaves: sudo nmcli connection add type ethernet con-name bond0-slave1 ifname eth0 master bond0',
            '4. Add slave 2: sudo nmcli connection add type ethernet con-name bond0-slave2 ifname eth1 master bond0',
            '5. Create VLAN 100 (Mgmt): sudo nmcli connection add type vlan con-name bond0.100 ifname bond0.100 vlan.parent bond0 vlan.id 100 ipv4.addresses "10.10.1.50/24" ipv4.gateway "10.10.1.1" ipv4.dns "10.10.1.10" ipv4.method manual',
            '6. Create VLAN 200 (Production): sudo nmcli connection add type vlan con-name bond0.200 ifname bond0.200 vlan.parent bond0 vlan.id 200',
            '7. Create VLAN 300 (Storage): sudo nmcli connection add type vlan con-name bond0.300 ifname bond0.300 vlan.parent bond0 vlan.id 300',
            '8. Create bridges: sudo nmcli connection add type bridge con-name br-mgmt ifname br-mgmt',
            '9. Activate: sudo nmcli connection up bond0 && sudo nmcli connection up bond0.100',
            '10. Verify: cat /proc/net/bonding/bond0',
        ],
        'common_mistakes': [
            'Switch not configured for LACP (Mode 4 requires matching switch config)',
            'Both NICs must go to same switch (or MLAG pair)',
            'Use nmcli (not ip commands) so config survives reboot',
            'Put host IP on VLAN interface (bond0.100), NOT on bond0 directly',
            'Dont bridge bond0 directly — bridge the VLAN sub-interfaces',
        ],
        'bond_modes': 'mode=0 (round-robin), mode=1 (active-backup, no switch config needed), mode=4 (802.3ad/LACP, best for production), mode=6 (adaptive load balance)',
    },
    {
        'title': 'Post-Installation Verification Checklist',
        'category': 'Installation',
        'products': ['VME', 'Morpheus'],
        'description': 'Verify all services are running after Manager appliance deployment.',
        'checks': [
            'All services: sudo morpheus-ctl status → All running',
            'Web UI: curl -kI https://<url> → HTTP 200',
            'Database: sudo morpheus-ctl db-status → MySQL active',
            'RabbitMQ: sudo rabbitmqctl status → Node running',
            'Elasticsearch: curl -s localhost:9200/_cluster/health → Status: green',
        ],
        'first_time_setup': [
            '1. Create primary admin Tenant profile + login credentials',
            '2. Configure monitoring hooks, log paths, backup rotations',
            '3. Enter entitlement key (or leave blank for 30-day trial)',
            '4. Link compute into Private Clouds and workload Groups',
        ],
    },
    # === VM MANAGEMENT ===
    {
        'title': 'KVM/libvirt VM Lifecycle Commands',
        'category': 'VM Management',
        'products': ['KVM', 'VME'],
        'description': 'Complete virsh command reference for VM lifecycle operations.',
        'commands': {
            'List running VMs': 'virsh list',
            'List all VMs': 'virsh list --all',
            'Start VM': 'virsh start <vm>',
            'Graceful shutdown': 'virsh shutdown <vm>',
            'Force power-off': 'virsh destroy <vm> (like pulling power cord - use only when unresponsive)',
            'Reboot': 'virsh reboot <vm>',
            'Suspend': 'virsh suspend <vm>',
            'Resume': 'virsh resume <vm>',
            'Enable auto-start': 'virsh autostart <vm>',
            'Disable auto-start': 'virsh autostart --disable <vm>',
            'Delete VM permanently': 'virsh undefine <vm> --remove-all-storage (IRREVERSIBLE)',
            'Rename VM': 'virsh domrename <old> <new> (VM must be off)',
        },
    },
    {
        'title': 'VM Resource Inspection and Hot-Add',
        'category': 'VM Management',
        'products': ['KVM', 'VME'],
        'description': 'Inspect VM resources and add CPU/memory/disk without downtime.',
        'inspection_commands': {
            'VM details': 'virsh dominfo <vm>',
            'CPU/memory stats': 'virsh domstats <vm>',
            'Full XML config': 'virsh dumpxml <vm>',
            'Edit config': 'virsh edit <vm>',
            'Show disks': 'virsh domblklist <vm>',
            'Show NICs': 'virsh domiflist <vm>',
            'Console access': 'virsh console <vm>',
            'OS/filesystem info': 'virsh domfsinfo <vm> (requires qemu-guest-agent)',
        },
        'hot_add': {
            'Add CPU cores': 'virsh setvcpus <vm> 4 --live',
            'Set max CPUs': 'virsh setvcpus <vm> 8 --config --maximum',
            'Add memory': 'virsh setmem <vm> 8G --live',
            'Set max memory': 'virsh setmaxmem <vm> 16G --config (requires restart)',
            'Attach disk': 'virsh attach-disk <vm> /path/disk.qcow2 vdb --live',
            'Detach disk': 'virsh detach-disk <vm> vdb --live (unmount inside VM first)',
            'Attach NIC': 'virsh attach-interface <vm> network default --live',
        },
    },
    {
        'title': 'VM Snapshot Management',
        'category': 'VM Management',
        'products': ['KVM', 'VME'],
        'description': 'Create, list, revert, and delete VM snapshots.',
        'commands': {
            'Create snapshot': 'virsh snapshot-create-as <vm> --name "pre-patch-july2026"',
            'List snapshots': 'virsh snapshot-list <vm>',
            'Revert to snapshot': 'virsh snapshot-revert <vm> --snapshotname "pre-patch-july2026"',
            'Delete snapshot': 'virsh snapshot-delete <vm> --snapshotname "pre-patch-july2026"',
            'Current snapshot': 'virsh snapshot-current <vm>',
        },
        'best_practices': [
            'Dont keep snapshots > 48-72 hours — they grow and slow disk I/O',
            'Always name descriptively: "pre-patch-july2026" not "snap1"',
            'Take when VM is idle — for DB VMs, quiesce DB first',
            'Delete immediately after confirming success',
        ],
    },
    # === NETWORKING ===
    {
        'title': 'Virtual Network Management',
        'category': 'Networking',
        'products': ['KVM', 'VME'],
        'description': 'Virtual network and physical network verification commands.',
        'virtual_network_commands': {
            'List active networks': 'virsh net-list',
            'List all networks': 'virsh net-list --all',
            'Network details': 'virsh net-info <net>',
            'Show XML config': 'virsh net-dumpxml <net>',
            'Start network': 'virsh net-start <net>',
            'Stop network': 'virsh net-destroy <net>',
            'Auto-start': 'virsh net-autostart <net>',
            'Create from XML': 'virsh net-define /path/network.xml',
            'Delete network': 'virsh net-undefine <net>',
        },
        'physical_verification': {
            'Show bridges': 'brctl show',
            'Bond status': 'cat /proc/net/bonding/bond0',
            'IP addresses': 'ip addr show',
            'Routing table': 'ip route show',
            'DNS resolution': 'nslookup <appliance-url>',
            'VLAN config': 'cat /proc/net/vlan/config',
            'Open ports': 'ss -tulnp',
            'Connectivity test': 'nc -zv <ip> 443',
        },
    },
    {
        'title': 'VM Network Troubleshooting - Cannot Reach External Network',
        'category': 'Networking',
        'products': ['KVM', 'VME'],
        'description': 'Debug flow when VMs cannot reach external networks.',
        'debug_steps': [
            '1. Check VM interfaces: virsh domiflist <vm>',
            '2. Check network info: virsh net-info <network>',
            '3. Check bridges: brctl show',
            '4. Check bond: cat /proc/net/bonding/bond0',
            '5. Check IP forwarding: sudo sysctl net.ipv4.ip_forward',
            '6. Fix: sudo sysctl -w net.ipv4.ip_forward=1',
        ],
    },
    # === STORAGE ===
    {
        'title': 'Storage Pool and Disk Management',
        'category': 'Storage',
        'products': ['KVM', 'VME'],
        'description': 'Manage storage pools, volumes, and disk images.',
        'pool_commands': {
            'List pools': 'virsh pool-list --all',
            'Pool details': 'virsh pool-info <pool>',
            'Refresh metadata': 'virsh pool-refresh <pool>',
            'List volumes': 'virsh vol-list <pool>',
            'Volume path': 'virsh vol-path --pool <pool> <vol>',
            'Create volume': 'virsh vol-create-as <pool> name.qcow2 50G --format qcow2',
            'Delete volume': 'virsh vol-delete --pool <pool> <vol>',
            'Clone volume': 'virsh vol-clone --pool <pool> <src> <dest>',
            'Resize volume': 'virsh vol-resize --pool <pool> <vol> 100G',
        },
        'qemu_img_commands': {
            'Disk info': 'qemu-img info /path/disk.qcow2',
            'Create disk': 'qemu-img create -f qcow2 /path/new.qcow2 100G',
            'Resize disk': 'qemu-img resize /path/disk.qcow2 +50G',
            'Convert format': 'qemu-img convert -f raw -O qcow2 in.raw out.qcow2',
            'Check integrity': 'qemu-img check /path/disk.qcow2',
            'Actual usage': 'du -sh /var/lib/libvirt/images/*.qcow2',
        },
        'storage_types': {
            'Local': '/var/lib/libvirt/images/ — fastest I/O but no live migration',
            'NFS': 'nfs-server:/exports/vms → /mnt/nfs-pool — shared, enables live migration',
            'LVM/iSCSI': '/dev/vg_hpevm/lv_vmdata — best for high-I/O workloads (databases)',
        },
    },
    # === TROUBLESHOOTING ===
    {
        'title': 'Manager Appliance UI Not Loading (HTTP 502/503)',
        'category': 'Troubleshooting',
        'products': ['VME', 'Morpheus'],
        'severity': 'Critical',
        'symptoms': 'Browser shows 502 Bad Gateway or blank page. Users cannot access management console.',
        'root_causes': 'morpheus-ui service crashed, Nginx misconfiguration, RAM exhaustion, DB connection pool full.',
        'resolution': [
            '1. sudo morpheus-ctl status (check which service is down)',
            '2. free -h (check if RAM is exhausted)',
            '3. sudo morpheus-ctl tail morpheus-ui (check for errors)',
            '4. sudo morpheus-ctl restart morpheus-ui',
            '5. sudo morpheus-ctl restart nginx (if nginx is the problem)',
            '6. Full reset: sudo morpheus-ctl stop && sleep 10 && sudo morpheus-ctl start',
            '7. sudo morpheus-ctl reconfigure (regenerate configs)',
        ],
    },
    {
        'title': 'VM Wont Start — Cannot access storage file',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Critical',
        'symptoms': 'virsh start <vm> fails with permission or storage errors.',
        'root_causes': 'SELinux context wrong, disk file permissions, storage pool not active, disk corrupted.',
        'resolution': [
            '1. ls -laZ /var/lib/libvirt/images/myvm.qcow2 (check permissions + SELinux)',
            '2. sudo chown qemu:qemu /var/lib/libvirt/images/myvm.qcow2',
            '3. sudo restorecon -Rv /var/lib/libvirt/images/ (fix SELinux labels)',
            '4. qemu-img check /var/lib/libvirt/images/myvm.qcow2 (check disk integrity)',
            '5. virsh pool-refresh default (refresh storage pool)',
        ],
    },
    {
        'title': 'All VMs Lost After Host Reboot',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Critical',
        'symptoms': 'After host reboot, virsh list --all shows no VMs.',
        'root_causes': 'libvirtd not started, VMs not set to autostart, definitions lost.',
        'resolution': [
            '1. sudo systemctl start libvirtd',
            '2. ls /etc/libvirt/qemu/ (VM definitions should be here)',
            '3. virsh define /backup/myvm.xml (re-define from backup XML)',
            '4. virsh autostart myvm (prevent this in future)',
        ],
        'prevention': 'Always virsh autostart production VMs + backup XMLs weekly.',
    },
    {
        'title': 'MySQL/Database Wont Start',
        'category': 'Troubleshooting',
        'products': ['VME', 'Morpheus'],
        'severity': 'Critical',
        'symptoms': 'Manager UI shows errors, morpheus-ctl status shows MySQL stopped.',
        'root_causes': 'Disk full, InnoDB crash, corrupted tables, stale PID file.',
        'resolution': [
            '1. df -h /opt/morpheus (check disk space)',
            '2. sudo rm -f /opt/morpheus/embedded/var/mysql/*.pid (remove stale PID)',
            '3. sudo journalctl --vacuum-time=3d (free space from old logs)',
            '4. sudo morpheus-ctl start mysql',
            '5. sudo morpheus-ctl db-repair (repair corrupted tables)',
        ],
    },
    {
        'title': 'Live Migration Fails',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Critical',
        'symptoms': 'virsh migrate --live errors: timeout, unable to connect, CPU incompatible.',
        'resolution': [
            '1. ssh root@target-host "virsh version" (test SSH connectivity)',
            '2. sudo firewall-cmd --permanent --add-port=49152-49215/tcp && sudo firewall-cmd --reload',
            '3. virsh capabilities | grep -i "model" (CPU model must match)',
            '4. Use CPU mode host-model instead of host-passthrough for easier migration',
        ],
    },
    {
        'title': 'VM Extremely Slow — High I/O Wait',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Performance',
        'symptoms': 'VM slow, top shows high %wa, apps timeout.',
        'root_causes': 'Disk I/O bottleneck, old snapshots degrading performance, wrong cache mode.',
        'resolution': [
            '1. iostat -xz 1 3 (check host disk utilization)',
            '2. virsh snapshot-list myvm (old snapshots = I/O penalty)',
            '3. virsh snapshot-delete myvm --snapshotname old-snap (delete to free I/O)',
            '4. Change disk cache to writeback: cache="writeback" io="native" in disk XML',
            '5. Move high-I/O VMs to SSD/NVMe storage',
        ],
    },
    {
        'title': 'VM Network Drops / Packet Loss',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Performance',
        'symptoms': 'Ping drops, SSH disconnects, intermittent connectivity.',
        'root_causes': 'MTU mismatch between host bond, bridge, and VM.',
        'resolution': [
            '1. virsh domifstat myvm vnet0 (check TX/RX errors)',
            '2. cat /proc/net/bonding/bond0 (both slaves active?)',
            '3. ip -s link show br0 (errors on bridge?)',
            '4. Fix: Ensure host bond, bridge, and VM all use same MTU (1500)',
        ],
    },
    {
        'title': 'Host OOM — VMs Getting Killed',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Critical',
        'symptoms': 'VMs crash randomly, dmesg shows "Out of memory: Kill process".',
        'root_causes': 'Memory overcommit beyond safe limits.',
        'resolution': [
            '1. free -h (check available RAM)',
            '2. dmesg | grep -i "oom\\|out of memory" (see what was killed)',
            '3. virsh shutdown <non-critical-vm> (free RAM immediately)',
            '4. echo 1 > /sys/kernel/mm/ksm/run (enable memory dedup)',
            '5. Rule: Dont overcommit beyond 1.5x physical RAM',
        ],
    },
    {
        'title': 'VM Shows 100% CPU But Host Is Idle',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Performance',
        'symptoms': 'VM maxed out but host has free CPUs.',
        'resolution': [
            '1. virsh dominfo myvm | grep "CPU" (check vCPU count)',
            '2. virsh setvcpus myvm 8 --live (hot-add more vCPUs)',
            '3. virsh numatune myvm --mode strict --nodeset 0 (pin to NUMA node)',
        ],
    },
    {
        'title': 'Disk Full — VMs Paused',
        'category': 'Troubleshooting',
        'products': ['KVM', 'VME'],
        'severity': 'Critical',
        'symptoms': 'VMs suddenly pause, cannot create new VMs.',
        'resolution': [
            '1. df -hT /var/lib/libvirt/images (check storage usage)',
            '2. du -sh /var/lib/libvirt/images/* | sort -h (find biggest files)',
            '3. virsh snapshot-delete <vm> --snapshotname old (delete old snapshots)',
            '4. virsh resume <vm> (resume paused VMs after freeing space)',
        ],
    },
    {
        'title': 'RabbitMQ Stuck — Provisioning Jobs Hang',
        'category': 'Troubleshooting',
        'products': ['VME', 'Morpheus'],
        'severity': 'Critical',
        'symptoms': 'New VM provisioning stuck at "Queued", tasks pile up.',
        'resolution': [
            '1. sudo rabbitmqctl list_queues name messages (check queue depths)',
            '2. sudo morpheus-ctl restart rabbitmq',
            '3. sudo morpheus-ctl restart morpheus-ui (reconnect UI to queue)',
        ],
    },
    {
        'title': 'Elasticsearch Red — Logs Not Working',
        'category': 'Troubleshooting',
        'products': ['VME', 'Morpheus'],
        'severity': 'Critical',
        'symptoms': 'Log search empty, dashboard incomplete.',
        'resolution': [
            '1. curl -s localhost:9200/_cluster/health?pretty (check status)',
            '2. curl -X DELETE localhost:9200/morpheus-logs-2026.05.* (delete old indices)',
            '3. curl -X POST localhost:9200/_cluster/reroute?retry_failed=true',
            '4. sudo morpheus-ctl restart elasticsearch',
        ],
    },
    {
        'title': 'Time Drift — Auth/SSL Failing',
        'category': 'Troubleshooting',
        'products': ['VME', 'KVM'],
        'severity': 'Critical',
        'symptoms': 'SSL errors, AD auth fails, timestamps wrong.',
        'resolution': [
            '1. timedatectl (check NTP sync)',
            '2. sudo chronyc makestep (force immediate sync)',
            '3. sudo systemctl restart chronyd',
        ],
    },
    {
        'title': 'Appliance Upgrade Failed',
        'category': 'Troubleshooting',
        'products': ['VME', 'Morpheus'],
        'severity': 'Critical',
        'symptoms': 'Upgrade hangs, mixed service versions.',
        'resolution': [
            '1. sudo morpheus-ctl stop',
            '2. sudo morpheus-ctl reconfigure',
            '3. sudo morpheus-ctl start',
            '4. If broken beyond repair: sudo morpheus-ctl backup restore /backup/pre-upgrade.tar.gz',
        ],
        'prevention': 'ALWAYS backup before upgrade: sudo morpheus-ctl backup create',
    },
    # === PRODUCTION SCENARIOS ===
    {
        'title': 'Production VM Unresponsive — Emergency Recovery',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'App team reports DB VM not responding. SSH and ping fail.',
        'resolution': [
            '1. virsh list --all | grep -i db-prod (check state)',
            '2. virsh console db-prod-vm (try console access)',
            '3. virsh snapshot-create-as db-prod-vm --name "pre-force-$(date +%Y%m%d%H%M)" (snapshot first)',
            '4. virsh destroy db-prod-vm && sleep 5 && virsh start db-prod-vm (force restart)',
        ],
        'notes': 'If running but unreachable, check network first before force restart.',
    },
    {
        'title': 'Deploy New VM for Dev Team',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'Provision a new VM: 4 vCPU, 8GB RAM, 100GB disk, specific VLAN.',
        'steps': [
            '1. qemu-img create -f qcow2 /var/lib/libvirt/images/dev-app-01.qcow2 100G',
            '2. virt-install --name dev-app-01 --ram 8192 --vcpus 4 --disk path=/var/lib/libvirt/images/dev-app-01.qcow2,format=qcow2 --os-variant centos-stream9 --network network=vlan150 --cdrom /var/lib/libvirt/images/CentOS-9.iso --graphics vnc,listen=0.0.0.0 --noautoconsole',
            '3. virsh autostart dev-app-01',
        ],
    },
    {
        'title': 'Host Memory Pressure — All VMs Slow',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'Multiple teams report slowness due to host memory pressure.',
        'resolution': [
            '1. free -h (check available RAM)',
            '2. ps aux --sort=-%mem | head -15 (find memory hogs)',
            '3. virsh setmem <non-critical-vm> 2G --live (reduce non-critical VM memory)',
            '4. virsh shutdown <test-vm> (shutdown idle VMs)',
        ],
    },
    {
        'title': 'Expand Disk — Zero Downtime',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'Add storage to a production VM without any downtime.',
        'steps': [
            '1. virsh domblklist prod-web-01 (find disk path)',
            '2. virsh blockresize prod-web-01 /var/lib/libvirt/images/prod-web-01.qcow2 150G',
            '3. Inside VM: sudo growpart /dev/vda 2 && sudo xfs_growfs / && df -h /',
        ],
    },
    {
        'title': 'SSL Certificate Expired',
        'category': 'Production Scenarios',
        'products': ['VME', 'Morpheus'],
        'description': 'Browser shows "not secure", API calls fail.',
        'resolution': [
            '1. echo | openssl s_client -connect <appliance>:443 2>/dev/null | openssl x509 -noout -dates',
            '2. sudo morpheus-ctl stop nginx',
            '3. sudo morpheus-ctl generate-ssl-cert',
            '4. sudo morpheus-ctl reconfigure && sudo morpheus-ctl start nginx',
        ],
    },
    {
        'title': 'Live Migration for Host Maintenance',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'Move all VMs to another host before firmware upgrade.',
        'steps': [
            '1. for vm in $(virsh list --name); do echo "Migrating $vm..."; virsh migrate --live --persistent --verbose $vm qemu+ssh://host02/system; done',
            '2. virsh list --all (should show empty on source host)',
        ],
    },
    {
        'title': 'New VLAN Provisioned by Network Team',
        'category': 'Production Scenarios',
        'products': ['KVM', 'VME'],
        'description': 'VLAN tagged on bond0, make it available for VMs.',
        'steps': [
            '1. sudo ip link add link bond0 name bond0.250 type vlan id 250',
            '2. sudo ip link set bond0.250 up',
            '3. sudo brctl addbr br-vlan250 && sudo brctl addif br-vlan250 bond0.250 && sudo ip link set br-vlan250 up',
            '4. virsh net-define /tmp/vlan250.xml && virsh net-start vlan250-prod && virsh net-autostart vlan250-prod',
        ],
    },
    # === MONITORING & DAILY OPS ===
    {
        'title': 'Monitoring and Health Checks',
        'category': 'Monitoring',
        'products': ['VME', 'KVM', 'Morpheus'],
        'description': 'Daily health check commands for HPE VM environment.',
        'appliance_health': {
            'All services': 'sudo morpheus-ctl status',
            'Restart service': 'sudo morpheus-ctl restart morpheus-ui',
            'Live app logs': 'sudo morpheus-ctl tail morpheus-ui',
            'Disk space': 'df -hT | grep -v tmpfs (<85% used)',
            'Memory': 'free -h (Available > 2GB)',
            'CPU load': 'uptime (Load < CPU cores)',
            'KVM ready': 'kvm-ok',
            'Libvirt daemon': 'sudo systemctl status libvirtd',
        },
        'per_vm_performance': {
            'CPU stats': 'virsh cpu-stats <vm>',
            'Memory stats': 'virsh dommemstat <vm>',
            'Disk I/O': 'virsh domblkstat <vm> vda',
            'Network I/O': 'virsh domifstat <vm> vnet0',
            'All VMs overview': 'virt-top',
            'System I/O': 'iostat -xz 1 5',
        },
        'log_locations': {
            'Morpheus UI': '/var/log/morpheus/morpheus-ui/current',
            'Elasticsearch': '/var/log/morpheus/elasticsearch/current',
            'MySQL': '/var/log/morpheus/mysql/current',
            'RabbitMQ': '/var/log/morpheus/rabbitmq/current',
            'Nginx': '/var/log/morpheus/nginx/current',
            'Per-VM logs': '/var/log/libvirt/qemu/<vm>.log',
            'Journal': 'journalctl -u libvirtd --since "1 hour ago"',
        },
    },
    # === BACKUP & DR ===
    {
        'title': 'Backup and Disaster Recovery',
        'category': 'Backup & DR',
        'products': ['KVM', 'VME', 'Morpheus'],
        'description': 'VM backup, appliance backup, and live migration commands.',
        'vm_backup': {
            'Snapshot (live)': 'virsh snapshot-create-as <vm> --name "backup-$(date +%Y%m%d)"',
            'Export disk (cold)': 'cp /var/lib/libvirt/images/<vm>.qcow2 /backup/',
            'Export XML config': 'virsh dumpxml <vm> > /backup/<vm>.xml',
            'Restore from XML': 'virsh define /backup/<vm>.xml && virsh start <vm>',
        },
        'appliance_backup': {
            'Create backup': 'sudo morpheus-ctl backup create',
            'List backups': 'sudo morpheus-ctl backup list',
            'Restore': 'sudo morpheus-ctl backup restore /path/backup.tar.gz',
            'Auto backup (cron)': '0 2 * * * /opt/morpheus/bin/morpheus-ctl backup create',
        },
        'live_migration': {
            'Live migrate': 'virsh migrate --live <vm> qemu+ssh://host2/system',
            'Offline migrate': 'virsh migrate --offline --persistent <vm> qemu+ssh://host2/system',
        },
    },
    # === SECURITY ===
    {
        'title': 'Security Hardening',
        'category': 'Security',
        'products': ['VME', 'KVM'],
        'description': 'Firewall, SELinux, SSH hardening, and audit commands.',
        'firewall': {
            'Status': 'sudo firewall-cmd --state',
            'List rules': 'sudo firewall-cmd --list-all',
            'Open 443': 'sudo firewall-cmd --permanent --add-port=443/tcp && sudo firewall-cmd --reload',
            'Migration ports': 'sudo firewall-cmd --permanent --add-port=49152-49215/tcp && sudo firewall-cmd --reload',
        },
        'selinux': {
            'Status': 'getenforce',
            'Fix disk labels': 'sudo restorecon -Rv /var/lib/libvirt/images/',
            'View denials': 'sudo ausearch -m avc -ts recent',
            'Generate fix': 'sudo ausearch -m avc -ts recent | audit2allow -M fix && sudo semodule -i fix.pp',
        },
        'audit': {
            'Failed SSH logins': 'journalctl -u sshd | grep "Failed" | tail -20',
            'Active sessions': 'who && w',
            'Sudo history': 'grep "COMMAND" /var/log/secure | tail -20',
            'Listening ports': 'sudo ss -tulnp | grep LISTEN',
        },
    },
    # === PERFORMANCE ===
    {
        'title': 'Performance Tuning',
        'category': 'Performance',
        'products': ['KVM', 'VME'],
        'description': 'Host-level optimization and benchmarking commands.',
        'tuning': {
            'Enable KSM (RAM dedup)': 'echo 1 > /sys/kernel/mm/ksm/run',
            'NUMA topology': 'numactl --hardware',
            'Pin to NUMA': 'virsh numatune <vm> --mode strict --nodeset 0',
            'CPU pinning': 'virsh vcpupin <vm> 0 2-3',
            'Hugepages': 'sysctl -w vm.nr_hugepages=1024',
            'I/O scheduler (SSD)': 'echo none > /sys/block/sda/queue/scheduler',
        },
        'benchmarks': {
            'Disk speed': 'dd if=/dev/zero of=/tmp/test bs=1M count=1024 oflag=direct',
            'Network': 'iperf3 -c <target> -t 10',
            'CPU': 'sysbench cpu --cpu-max-prime=20000 run',
            'I/O': 'fio --name=test --ioengine=libaio --bs=4k --numjobs=4 --size=1G --rw=randread',
        },
        'db_vm_fix': 'Change cache="none" to cache="writeback" io="native" in disk XML for DB VMs with high I/O wait.',
    },
    # === VMWARE MIGRATION ===
    {
        'title': 'VMware to KVM Migration Guide',
        'category': 'Migration',
        'products': ['VME', 'KVM'],
        'description': 'Converting VMware VMs to KVM using virt-v2v tool.',
        'command': 'virt-v2v -i vmx /path/to/vm.vmx -o local -os /var/lib/libvirt/images/',
        'notes': 'Handles driver injection (virtio) and boot config changes automatically.',
        'command_mapping': {
            'List VMs': 'VMware: vim-cmd vmsvc/getallvms → KVM: virsh list --all',
            'Power on': 'VMware: vim-cmd vmsvc/power.on <vmid> → KVM: virsh start <vm>',
            'Power off': 'VMware: vim-cmd vmsvc/power.off <vmid> → KVM: virsh destroy <vm>',
            'Shutdown': 'VMware: vim-cmd vmsvc/power.shutdown <vmid> → KVM: virsh shutdown <vm>',
            'Snapshot': 'VMware: vim-cmd vmsvc/snapshot.create → KVM: virsh snapshot-create-as <vm> --name "snap1"',
            'Live migrate': 'VMware: Invoke-VMotion → KVM: virsh migrate --live <vm> qemu+ssh://dest/system',
            'Console': 'VMware: VMRC/Web Console → KVM: virsh console <vm> or VNC/SPICE',
        },
    },
    # === QUICK DIAGNOSTICS ===
    {
        'title': 'Quick Diagnostics Decision Tree',
        'category': 'Troubleshooting',
        'products': ['VME', 'KVM', 'Morpheus'],
        'description': 'Rapid diagnosis guide: symptom → first command → likely cause → quick fix.',
        'diagnostics': {
            'UI not loading': {'cmd': 'morpheus-ctl status', 'cause': 'UI service crashed', 'fix': 'morpheus-ctl restart morpheus-ui'},
            'VM wont start': {'cmd': 'virsh start vm 2>&1', 'cause': 'Permission/SELinux', 'fix': 'restorecon + chown qemu:qemu'},
            'VM slow': {'cmd': 'iostat -xz 1', 'cause': 'Disk I/O bottleneck', 'fix': 'Delete snapshots, use SSD'},
            'Network down': {'cmd': 'brctl show', 'cause': 'Bridge/VLAN issue', 'fix': 'Check bond + MTU'},
            'Host OOM': {'cmd': 'free -h', 'cause': 'Memory overcommit', 'fix': 'Shutdown idle VMs, enable KSM'},
            'Jobs stuck': {'cmd': 'rabbitmqctl list_queues', 'cause': 'RabbitMQ hung', 'fix': 'morpheus-ctl restart rabbitmq'},
            'Auth failing': {'cmd': 'timedatectl', 'cause': 'Clock drift', 'fix': 'chronyc makestep'},
            'Backup failing': {'cmd': 'df -h /opt/morpheus', 'cause': 'Disk full', 'fix': 'Clean old logs/backups'},
            'SSL errors': {'cmd': 'openssl s_client', 'cause': 'Cert expired', 'fix': 'morpheus-ctl generate-ssl-cert'},
            'Migration fails': {'cmd': 'ssh target virsh version', 'cause': 'SSH/firewall/CPU', 'fix': 'Exchange keys, open ports'},
        },
    },
    # === DAILY OPS SCRIPTS ===
    {
        'title': 'Daily Operations Scripts and Checklists',
        'category': 'Daily Ops',
        'products': ['VME', 'KVM', 'Morpheus'],
        'description': 'Scripts and checklists for daily, weekly, and monthly operations.',
        'morning_health_script': '#!/bin/bash\n# HPE VM Daily Health\necho "== HPE VM Health Report — $(date) =="\nuptime\nfree -h\ndf -hT | grep -v tmpfs\nsudo systemctl is-active libvirtd\nvirsh list\nsudo morpheus-ctl status\nvirsh pool-list --all\njournalctl --since "1 hour ago" -p err --no-pager | tail -15',
        'weekly_tasks': {
            'Backup appliance': 'sudo morpheus-ctl backup create',
            'Rotate logs': 'sudo logrotate -f /etc/logrotate.d/morpheus',
            'Find orphan disks': 'find /var/lib/libvirt/images -name "*.qcow2" -mtime +30',
            'Count snapshots': 'for vm in $(virsh list --name); do echo "$vm: $(virsh snapshot-list $vm --name | wc -l)"; done',
            'NTP sync check': 'chronyc tracking',
            'SSL cert expiry': 'echo | openssl s_client -connect localhost:443 2>/dev/null | openssl x509 -noout -enddate',
        },
        'monthly_tasks': {
            'Security patches': 'sudo yum update --security -y',
            'Review VM resources': 'for vm in $(virsh list --all --name); do echo "==$vm=="; virsh dominfo $vm | grep -E "CPU|Memory"; done',
            'Clean old backups': 'find /backup -name "*.tar.gz" -mtime +30 -delete',
            'DR readiness': 'sudo morpheus-ctl backup list | tail -5',
        },
    },
    # === STORAGE VALIDATION & HEALTH MONITORING ===
    {
        'title': 'SCSI-3 Persistent Reservation (PR) Key Cluster Validation',
        'category': 'Storage Validation',
        'products': ['GFS2', 'KVM'],
        'description': 'Validates SCSI-3 PR keys are correctly registered on all multipath paths across all cluster nodes. PR keys are the mechanism GFS2 uses for I/O fencing — if a node misbehaves, other nodes can eject it from the shared LUN using PR commands.',
        'what_it_checks': [
            'Reads cluster members from /etc/corosync/corosync.conf',
            'Finds GFS2 datastores from lsblk (fstype=gfs2 on multipath devices)',
            'Maps GFS2 UUID to WWID',
            'Runs multipath -ll <WWID> to find all backing sdX devices',
            'Runs sg_persist --in --read-key /dev/sdX on each path',
            'Compares returned PR keys with reservation_key from /etc/multipath.conf',
            'Compares PR key visibility across all hosts and all sdX paths',
        ],
        'status_codes': {
            'OK_CONFIG_KEY_PRESENT': 'All good — config key found in read keys on this path',
            'MISSING_CONFIG_KEY': 'CRITICAL — configured reservation_key NOT in sg_persist output. Node cannot be fenced properly.',
            'MISSING_ALL_PR_KEYS': 'CRITICAL — No PR keys returned at all. Device may not support PR or keys were cleared.',
            'NO_KEYS_RETURNED': 'sg_persist returned empty. Check device path validity.',
            'WARNING_NO_CONFIG_KEY': 'No reservation_key found in multipath.conf — cannot validate.',
            'SG_PERSIST_FAILED': 'sg_persist command itself failed — check device access.',
            'DEVICE_MISSING': 'sdX device does not exist as a block device.',
            'MPATH_FAILED': 'multipath -ll failed for this WWID.',
        },
        'resolution': [
            '1. Run: sg_persist --in --read-keys /dev/sdX (see current registrations)',
            '2. Check config: grep reservation_key /etc/multipath.conf /etc/multipath/conf.d/*',
            '3. Register key: sg_persist --out --register --param-sark=0x<KEY> /dev/sdX',
            '4. Verify all paths: multipath -ll <WWID> then check each sdX',
            '5. Cross-host: run check on all nodes and compare',
            '6. If keys cleared: storage array may have been restarted — re-register on all nodes',
        ],
    },
    {
        'title': 'HPE VME Host Health Report Interpretation',
        'category': 'Health Monitoring',
        'products': ['VME', 'KVM', 'Morpheus'],
        'description': 'Understanding the health report output generated during HPE VM Essentials diagnostics with OK/WARN/CRIT ratings.',
        'health_checks': {
            'CPU Utilization': '>75% = WARN, >90% = CRIT. Fix: migrate VMs, reduce vCPUs, CPU pinning.',
            'Memory Used': '>85% = WARN, >95% = CRIT. Fix: shutdown idle VMs, enable KSM, add RAM.',
            'Disk Space': '>85% = WARN, >95% = CRIT. Fix: clean logs, delete snapshots, extend LVM.',
            'Cluster Quorum': 'Not quorate = CRIT. Fix: check corosync, network, node health.',
            'Failed Resources': 'Any = CRIT. Fix: pcs resource cleanup, check resource config.',
            'Multipath Paths': 'Faulty = CRIT. Fix: check FC/iSCSI, cables, switch ports.',
            'Network Interfaces': 'Down = WARN. Fix: check cable, switch port, ethtool, bond status.',
            'Critical Log Messages': 'Found = WARN. Review journal for root cause.',
        },
        'data_collected': {
            'System': 'hostnamectl, uptime, dmesg, ps, top, lsblk, df, mount, sysctl',
            'Appliance': 'morpheus-ctl status, morpheus.rb, /var/log/morpheus/, MySQL dump, version manifest',
            'KVM Host': '/var/log/*, morpheus-node-ctl status, ethtool, bonding, multipath, virsh commands',
            'Cluster (8.x)': 'pcs status/config/resource, crm, stonith, quorum',
            'Cluster (9.x)': 'corosync-quorumtool, dlm_tool, GFS2 withdraw status, .quorum-nodes, .hb files',
            'Storage': 'sg_persist (PR keys), sg_inq, sg_vpd, multipath -ll, virsh pool/vol',
            'Network': 'ip addr, ethtool (all NICs), bonding status, netplan, iptables, OVS',
            'VMs': 'virsh dumpxml/vcpuinfo/dommemstat/domblklist/domblkerror/domiflist per VM',
        },
        'node_detection': {
            'Appliance': 'morpheus-ctl command exists',
            'KVM (8.x)': 'morpheus-node-ctl exists + "run: morphd" in status (Pacemaker cluster)',
            'KVM (9.x)': 'morpheus-node-ctl exists + morpheus-node-ctl version works (DLM/GFS2 cluster)',
        },
    },
    {
        'title': 'Log Archive Extraction and Classification',
        'category': 'Log Analysis',
        'products': ['VME', 'KVM', 'Morpheus'],
        'description': 'Understanding how nested archives (tar/gz/bz2/xz/zip) are extracted and scanned for ERROR/WARN patterns in Morpheus/KVM/HVM log files.',
        'supported_formats': ['tar', 'tar.gz', 'gz', 'bz2', 'tar.bz2', 'xz', 'tar.xz', 'zip', 'lzma'],
        'log_file_patterns': [
            'morpheus*.log', 'kvm*.log', 'hvm*.log', 'libvirt*.log',
            'qemu*.log', 'syslog', 'messages', 'kern.log', 'dmesg',
            'daemon.log', 'cloud-init*.log', 'journalctl*',
            '*.log', '*.log.[0-9]', '*.out',
        ],
        'classification': {
            'ERROR': 'ERROR, SEVERE, FATAL, CRITICAL, EMERGENCY, ALERT',
            'WARN': 'WARNING, WARN',
        },
        'output': 'Per-file breakdown (errors/warns/lines) + CSV + TXT report with all flagged lines.',
        'notes': 'LogSherlock Pro uses 156 pattern signatures for much deeper analysis beyond simple ERROR/WARN classification.',
    },
]
